// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package gppmodel

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CacheStatus0.
const (
	EXPIRED CacheStatus0 = "EXPIRED"
	HIT     CacheStatus0 = "HIT"
	MISS    CacheStatus0 = "MISS"
)

// Valid indicates whether the value is a known member of the CacheStatus0 enum.
func (e CacheStatus0) Valid() bool {
	switch e {
	case EXPIRED:
		return true
	case HIT:
		return true
	case MISS:
		return true
	default:
		return false
	}
}

// Defines values for CellIdentifierType0.
const (
	CGI  CellIdentifierType0 = "CGI"
	ECGI CellIdentifierType0 = "ECGI"
	NCGI CellIdentifierType0 = "NCGI"
)

// Valid indicates whether the value is a known member of the CellIdentifierType0 enum.
func (e CellIdentifierType0) Valid() bool {
	switch e {
	case CGI:
		return true
	case ECGI:
		return true
	case NCGI:
		return true
	default:
		return false
	}
}

// Defines values for EASRelocationTolerance0.
const (
	RELOCATIONINTOLERANT EASRelocationTolerance0 = "RELOCATION_INTOLERANT"
	RELOCATIONTOLERANT   EASRelocationTolerance0 = "RELOCATION_TOLERANT"
	RELOCATIONUNAWARE    EASRelocationTolerance0 = "RELOCATION_UNAWARE"
)

// Valid indicates whether the value is a known member of the EASRelocationTolerance0 enum.
func (e EASRelocationTolerance0) Valid() bool {
	switch e {
	case RELOCATIONINTOLERANT:
		return true
	case RELOCATIONTOLERANT:
		return true
	case RELOCATIONUNAWARE:
		return true
	default:
		return false
	}
}

// Defines values for ProvisioningSessionType0.
const (
	DOWNLINK ProvisioningSessionType0 = "DOWNLINK"
	UPLINK   ProvisioningSessionType0 = "UPLINK"
)

// Valid indicates whether the value is a known member of the ProvisioningSessionType0 enum.
func (e ProvisioningSessionType0) Valid() bool {
	switch e {
	case DOWNLINK:
		return true
	case UPLINK:
		return true
	default:
		return false
	}
}

// Defines values for SdfMethod0.
const (
	DOMAINNAME           SdfMethod0 = "DOMAIN_NAME"
	FLOWLABEL            SdfMethod0 = "FLOW_LABEL"
	N2TUPLE              SdfMethod0 = "2_TUPLE"
	N5TUPLE              SdfMethod0 = "5_TUPLE"
	TYPEOFSERVICEMARKING SdfMethod0 = "TYPE_OF_SERVICE_MARKING"
)

// Valid indicates whether the value is a known member of the SdfMethod0 enum.
func (e SdfMethod0) Valid() bool {
	switch e {
	case DOMAINNAME:
		return true
	case FLOWLABEL:
		return true
	case N2TUPLE:
		return true
	case N5TUPLE:
		return true
	case TYPEOFSERVICEMARKING:
		return true
	default:
		return false
	}
}

// AbsoluteUrl Absolute Uniform Resource Locator, conforming with the "absolute-URI" production specified in IETF RFC 3986, section 4.3 in which the scheme part is "http" or "https". Note that the "query" suffix is permitted by this production but the "fragment" suffix is not.
type AbsoluteUrl = string

// CacheStatus defines model for CacheStatus.
type CacheStatus struct {
	union json.RawMessage
}

// CacheStatus0 defines model for CacheStatus.0.
type CacheStatus0 string

// CacheStatus1 This string provides forward-compatibility with future extensions to the enumeration but is not used to encode content defined in the present version of this API.
type CacheStatus1 = string

// CellIdentifierType defines model for CellIdentifierType.
type CellIdentifierType struct {
	union json.RawMessage
}

// CellIdentifierType0 defines model for CellIdentifierType.0.
type CellIdentifierType0 string

// CellIdentifierType1 This string provides forward-compatibility with future extensions to the enumeration but is not used to encode content defined in the present version of this API.
type CellIdentifierType1 = string

// ChargingSpecification defines model for ChargingSpecification.
type ChargingSpecification struct {
	Gpsi   *[]Gpsi `json:"gpsi,omitempty"`
	SponId *string `json:"sponId,omitempty"`

	// SponStatus Indicates whether sponsored data connectivity is enabled or disabled/not enabled.
	SponStatus *SponsoringStatus `json:"sponStatus,omitempty"`
}

// Duration String with format "duration" as defined by JSON Schema (referencing IETF RFC 3339, appendix A and, ultimately, ISO 8601).
type Duration = string

// EASRelocationTolerance defines model for EASRelocationTolerance.
type EASRelocationTolerance struct {
	union json.RawMessage
}

// EASRelocationTolerance0 defines model for EASRelocationTolerance.0.
type EASRelocationTolerance0 string

// EASRelocationTolerance1 This string provides forward-compatibility with future extensions to the enumeration but is not used to encode content defined in the present version of this API.
type EASRelocationTolerance1 = string

// EdgeProcessingEligibilityCriteria defines model for EdgeProcessingEligibilityCriteria.
type EdgeProcessingEligibilityCriteria struct {
	AppRequest                  bool                         `json:"appRequest"`
	ServiceDataFlowDescriptions []ServiceDataFlowDescription `json:"serviceDataFlowDescriptions"`
	TimeWindows                 []TimeWindow                 `json:"timeWindows"`
	UeLocations                 []LocationArea5G             `json:"ueLocations"`
}

// EndpointAddress defines model for EndpointAddress.
type EndpointAddress struct {
	Hostname *string `json:"hostname,omitempty"`

	// Ipv4Addr String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
	Ipv4Addr *Ipv4Addr `json:"ipv4Addr,omitempty"`

	// Ipv6Addr String identifying an IPv6 address formatted according to clause 4 of RFC5952. The mixed IPv4 IPv6 notation according to clause 5 of RFC5952 shall not be used.
	Ipv6Addr *Ipv6Addr `json:"ipv6Addr,omitempty"`

	// PortNumber Integer where the allowed values correspond to the value range of an unsigned 16-bit integer.
	PortNumber Uint16 `json:"portNumber"`
}

// IpPacketFilterSet defines model for IpPacketFilterSet.
type IpPacketFilterSet struct {
	Direction string  `json:"direction"`
	DstIp     *string `json:"dstIp,omitempty"`
	DstPort   *int    `json:"dstPort,omitempty"`
	FlowLabel *int    `json:"flowLabel,omitempty"`
	Protocol  *int    `json:"protocol,omitempty"`
	Spi       *int    `json:"spi,omitempty"`
	SrcIp     *string `json:"srcIp,omitempty"`
	SrcPort   *int    `json:"srcPort,omitempty"`
	ToSTc     *string `json:"toSTc,omitempty"`
}

// M1QoSSpecification defines model for M1QoSSpecification.
type M1QoSSpecification struct {
	DefPacketLossRateDl *int `json:"defPacketLossRateDl,omitempty"`
	DefPacketLossRateUl *int `json:"defPacketLossRateUl,omitempty"`

	// MaxAuthBtrDl String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
	MaxAuthBtrDl *BitRate `json:"maxAuthBtrDl,omitempty"`

	// MaxAuthBtrUl String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
	MaxAuthBtrUl *BitRate `json:"maxAuthBtrUl,omitempty"`

	// MaxBtrDl String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
	MaxBtrDl *BitRate `json:"maxBtrDl,omitempty"`

	// MaxBtrUl String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
	MaxBtrUl     *BitRate `json:"maxBtrUl,omitempty"`
	QosReference *string  `json:"qosReference,omitempty"`
}

// M5QoSSpecification defines model for M5QoSSpecification.
type M5QoSSpecification struct {
	DesLatency *int `json:"desLatency,omitempty"`
	DesLoss    *int `json:"desLoss,omitempty"`

	// MarBwDlBitRate String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
	MarBwDlBitRate BitRate `json:"marBwDlBitRate"`

	// MarBwUlBitRate String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
	MarBwUlBitRate BitRate `json:"marBwUlBitRate"`

	// MinDesBwDlBitRate String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
	MinDesBwDlBitRate *BitRate `json:"minDesBwDlBitRate,omitempty"`

	// MinDesBwUlBitRate String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
	MinDesBwUlBitRate *BitRate `json:"minDesBwUlBitRate,omitempty"`

	// MirBwDlBitRate String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
	MirBwDlBitRate BitRate `json:"mirBwDlBitRate"`

	// MirBwUlBitRate String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
	MirBwUlBitRate BitRate `json:"mirBwUlBitRate"`
}

// MediaDeliverySessionId A unique identifier for a media delivery session.
type MediaDeliverySessionId = string

// MediaStreamingAccess Common properties of a single media access by the Media Stream Handler.
type MediaStreamingAccess struct {
	ApplicationServerEndpointAddress EndpointAddress `json:"applicationServerEndpointAddress"`
	CacheStatus                      *CacheStatus    `json:"cacheStatus,omitempty"`
	ConnectionMetrics                *struct {
		// CongestionWindowSize Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
		CongestionWindowSize Uinteger `json:"congestionWindowSize"`

		// MeanNetworkRoundTripTime string with format 'float' as defined in OpenAPI.
		MeanNetworkRoundTripTime Float `json:"meanNetworkRoundTripTime"`

		// NetworkRoundTripTimeVariation string with format 'float' as defined in OpenAPI.
		NetworkRoundTripTimeVariation Float `json:"networkRoundTripTimeVariation"`
	} `json:"connectionMetrics,omitempty"`
	MediaStreamHandlerEndpointAddress EndpointAddress `json:"mediaStreamHandlerEndpointAddress"`

	// ProcessingLatency string with format 'float' as defined in OpenAPI.
	ProcessingLatency Float `json:"processingLatency"`
	RequestMessage    struct {
		// BodySize Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
		BodySize        Uinteger `json:"bodySize"`
		ContentType     *string  `json:"contentType,omitempty"`
		Method          string   `json:"method"`
		ProtocolVersion string   `json:"protocolVersion"`
		Range           *string  `json:"range,omitempty"`

		// Referer Absolute Uniform Resource Locator, conforming with the "absolute-URI" production specified in IETF RFC 3986, section 4.3 in which the scheme part is "http" or "https". Note that the "query" suffix is permitted by this production but the "fragment" suffix is not.
		Referer *AbsoluteUrl `json:"referer,omitempty"`

		// Size Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
		Size Uinteger `json:"size"`

		// Url Absolute Uniform Resource Locator, conforming with the "absolute-URI" production specified in IETF RFC 3986, section 4.3 in which the scheme part is "http" or "https". Note that the "query" suffix is permitted by this production but the "fragment" suffix is not.
		Url          AbsoluteUrl `json:"url"`
		UserAgent    *string     `json:"userAgent,omitempty"`
		UserIdentity *string     `json:"userIdentity,omitempty"`
	} `json:"requestMessage"`
	ResponseMessage struct {
		// BodySize Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
		BodySize    Uinteger `json:"bodySize"`
		ContentType *string  `json:"contentType,omitempty"`

		// ResponseCode Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
		ResponseCode Uinteger `json:"responseCode"`

		// Size Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
		Size Uinteger `json:"size"`
	} `json:"responseMessage"`
}

// MediaStreamingSessionIdentification defines model for MediaStreamingSessionIdentification.
type MediaStreamingSessionIdentification struct {
	// SessionId A unique identifier for a media delivery session.
	SessionId MediaDeliverySessionId `json:"sessionId"`
}

// NetworkAssistanceInvocation Common properties of a single Network Assistance invocation.
type NetworkAssistanceInvocation struct {
	// PolicyTemplateId String chosen by the 5GMS AF to serve as an identifier in a resource URI.
	PolicyTemplateId *ResourceId `json:"policyTemplateId,omitempty"`

	// RecommendedQoS The network QoS parameters (if any) recommended to the Media Session Handler.
	RecommendedQoS *struct {
		// MaximumBitRate String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
		MaximumBitRate BitRate `json:"maximumBitRate"`

		// MinimumBitRate String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
		MinimumBitRate BitRate `json:"minimumBitRate"`
	} `json:"recommendedQoS,omitempty"`

	// RequestedQoS A specification for network Quality of Service in either the downlink or uplink direction.
	RequestedQoS                *UnidirectionalQoSSpecification `json:"requestedQoS,omitempty"`
	ServiceDataFlowDescriptions *[]ServiceDataFlowDescription   `json:"serviceDataFlowDescriptions,omitempty"`
}

// OperationSuccessResponse defines model for OperationSuccessResponse.
type OperationSuccessResponse struct {
	Reason  *string `json:"reason,omitempty"`
	Success bool    `json:"success"`
}

// Percentage defines model for Percentage.
type Percentage = float32

// ProvisioningSessionType defines model for ProvisioningSessionType.
type ProvisioningSessionType struct {
	union json.RawMessage
}

// ProvisioningSessionType0 defines model for ProvisioningSessionType.0.
type ProvisioningSessionType0 string

// ProvisioningSessionType1 This string provides forward-compatibility with future extensions to the enumeration but is not used to encode content defined in the present version of this API.
type ProvisioningSessionType1 = string

// RelativeUrl Relative Uniform Resource Locator, conforming with the "relative-ref" production specified in IETF RFC 3986, section 4.2. Note that both "query" and "fragment" suffixes are permitted by this production.
type RelativeUrl = string

// SdfMethod defines model for SdfMethod.
type SdfMethod struct {
	union json.RawMessage
}

// SdfMethod0 defines model for SdfMethod.0.
type SdfMethod0 string

// SdfMethod1 This string provides forward-compatibility with future extensions to the enumeration but is not used to encode content defined in the present version of this API.
type SdfMethod1 = string

// ServiceDataFlowDescription defines model for ServiceDataFlowDescription.
type ServiceDataFlowDescription struct {
	DomainName      *string            `json:"domainName,omitempty"`
	FlowDescription *IpPacketFilterSet `json:"flowDescription,omitempty"`
}

// TypedLocation defines model for TypedLocation.
type TypedLocation struct {
	Location               string             `json:"location"`
	LocationIdentifierType CellIdentifierType `json:"locationIdentifierType"`
}

// UnidirectionalQoSSpecification A specification for network Quality of Service in either the downlink or uplink direction.
type UnidirectionalQoSSpecification struct {
	DesiredPacketLatency  *int `json:"desiredPacketLatency,omitempty"`
	DesiredPacketLossRate *int `json:"desiredPacketLossRate,omitempty"`

	// MaximumRequestedBitRate String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
	MaximumRequestedBitRate BitRate `json:"maximumRequestedBitRate"`

	// MinimumDesiredBitRate String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
	MinimumDesiredBitRate *BitRate `json:"minimumDesiredBitRate,omitempty"`

	// MinimumRequestedBitRate String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
	MinimumRequestedBitRate BitRate `json:"minimumRequestedBitRate"`
}

// Url Uniform Resource Locator, conforming with the "URI-reference" production specified in IETF RFC 3986, section 4.1.
type Url = string

// AsCacheStatus0 returns the union data inside the CacheStatus as a CacheStatus0
func (t CacheStatus) AsCacheStatus0() (CacheStatus0, error) {
	var body CacheStatus0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCacheStatus0 overwrites any union data inside the CacheStatus as the provided CacheStatus0
func (t *CacheStatus) FromCacheStatus0(v CacheStatus0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCacheStatus0 performs a merge with any union data inside the CacheStatus, using the provided CacheStatus0
func (t *CacheStatus) MergeCacheStatus0(v CacheStatus0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCacheStatus1 returns the union data inside the CacheStatus as a CacheStatus1
func (t CacheStatus) AsCacheStatus1() (CacheStatus1, error) {
	var body CacheStatus1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCacheStatus1 overwrites any union data inside the CacheStatus as the provided CacheStatus1
func (t *CacheStatus) FromCacheStatus1(v CacheStatus1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCacheStatus1 performs a merge with any union data inside the CacheStatus, using the provided CacheStatus1
func (t *CacheStatus) MergeCacheStatus1(v CacheStatus1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CacheStatus) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CacheStatus) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCellIdentifierType0 returns the union data inside the CellIdentifierType as a CellIdentifierType0
func (t CellIdentifierType) AsCellIdentifierType0() (CellIdentifierType0, error) {
	var body CellIdentifierType0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCellIdentifierType0 overwrites any union data inside the CellIdentifierType as the provided CellIdentifierType0
func (t *CellIdentifierType) FromCellIdentifierType0(v CellIdentifierType0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCellIdentifierType0 performs a merge with any union data inside the CellIdentifierType, using the provided CellIdentifierType0
func (t *CellIdentifierType) MergeCellIdentifierType0(v CellIdentifierType0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCellIdentifierType1 returns the union data inside the CellIdentifierType as a CellIdentifierType1
func (t CellIdentifierType) AsCellIdentifierType1() (CellIdentifierType1, error) {
	var body CellIdentifierType1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCellIdentifierType1 overwrites any union data inside the CellIdentifierType as the provided CellIdentifierType1
func (t *CellIdentifierType) FromCellIdentifierType1(v CellIdentifierType1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCellIdentifierType1 performs a merge with any union data inside the CellIdentifierType, using the provided CellIdentifierType1
func (t *CellIdentifierType) MergeCellIdentifierType1(v CellIdentifierType1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CellIdentifierType) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CellIdentifierType) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEASRelocationTolerance0 returns the union data inside the EASRelocationTolerance as a EASRelocationTolerance0
func (t EASRelocationTolerance) AsEASRelocationTolerance0() (EASRelocationTolerance0, error) {
	var body EASRelocationTolerance0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEASRelocationTolerance0 overwrites any union data inside the EASRelocationTolerance as the provided EASRelocationTolerance0
func (t *EASRelocationTolerance) FromEASRelocationTolerance0(v EASRelocationTolerance0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEASRelocationTolerance0 performs a merge with any union data inside the EASRelocationTolerance, using the provided EASRelocationTolerance0
func (t *EASRelocationTolerance) MergeEASRelocationTolerance0(v EASRelocationTolerance0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEASRelocationTolerance1 returns the union data inside the EASRelocationTolerance as a EASRelocationTolerance1
func (t EASRelocationTolerance) AsEASRelocationTolerance1() (EASRelocationTolerance1, error) {
	var body EASRelocationTolerance1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEASRelocationTolerance1 overwrites any union data inside the EASRelocationTolerance as the provided EASRelocationTolerance1
func (t *EASRelocationTolerance) FromEASRelocationTolerance1(v EASRelocationTolerance1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEASRelocationTolerance1 performs a merge with any union data inside the EASRelocationTolerance, using the provided EASRelocationTolerance1
func (t *EASRelocationTolerance) MergeEASRelocationTolerance1(v EASRelocationTolerance1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EASRelocationTolerance) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EASRelocationTolerance) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsProvisioningSessionType0 returns the union data inside the ProvisioningSessionType as a ProvisioningSessionType0
func (t ProvisioningSessionType) AsProvisioningSessionType0() (ProvisioningSessionType0, error) {
	var body ProvisioningSessionType0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProvisioningSessionType0 overwrites any union data inside the ProvisioningSessionType as the provided ProvisioningSessionType0
func (t *ProvisioningSessionType) FromProvisioningSessionType0(v ProvisioningSessionType0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProvisioningSessionType0 performs a merge with any union data inside the ProvisioningSessionType, using the provided ProvisioningSessionType0
func (t *ProvisioningSessionType) MergeProvisioningSessionType0(v ProvisioningSessionType0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProvisioningSessionType1 returns the union data inside the ProvisioningSessionType as a ProvisioningSessionType1
func (t ProvisioningSessionType) AsProvisioningSessionType1() (ProvisioningSessionType1, error) {
	var body ProvisioningSessionType1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProvisioningSessionType1 overwrites any union data inside the ProvisioningSessionType as the provided ProvisioningSessionType1
func (t *ProvisioningSessionType) FromProvisioningSessionType1(v ProvisioningSessionType1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProvisioningSessionType1 performs a merge with any union data inside the ProvisioningSessionType, using the provided ProvisioningSessionType1
func (t *ProvisioningSessionType) MergeProvisioningSessionType1(v ProvisioningSessionType1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ProvisioningSessionType) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ProvisioningSessionType) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSdfMethod0 returns the union data inside the SdfMethod as a SdfMethod0
func (t SdfMethod) AsSdfMethod0() (SdfMethod0, error) {
	var body SdfMethod0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSdfMethod0 overwrites any union data inside the SdfMethod as the provided SdfMethod0
func (t *SdfMethod) FromSdfMethod0(v SdfMethod0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSdfMethod0 performs a merge with any union data inside the SdfMethod, using the provided SdfMethod0
func (t *SdfMethod) MergeSdfMethod0(v SdfMethod0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSdfMethod1 returns the union data inside the SdfMethod as a SdfMethod1
func (t SdfMethod) AsSdfMethod1() (SdfMethod1, error) {
	var body SdfMethod1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSdfMethod1 overwrites any union data inside the SdfMethod as the provided SdfMethod1
func (t *SdfMethod) FromSdfMethod1(v SdfMethod1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSdfMethod1 performs a merge with any union data inside the SdfMethod, using the provided SdfMethod1
func (t *SdfMethod) MergeSdfMethod1(v SdfMethod1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SdfMethod) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SdfMethod) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
