// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package gppmodel

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for DataCollectionClientType0.
const (
	APPLICATIONSERVER DataCollectionClientType0 = "APPLICATION_SERVER"
	DIRECT            DataCollectionClientType0 = "DIRECT"
	INDIRECT          DataCollectionClientType0 = "INDIRECT"
)

// Valid indicates whether the value is a known member of the DataCollectionClientType0 enum.
func (e DataCollectionClientType0) Valid() bool {
	switch e {
	case APPLICATIONSERVER:
		return true
	case DIRECT:
		return true
	case INDIRECT:
		return true
	default:
		return false
	}
}

// DataCollectionClientType Indicating a type of data collection client that reports UE data to the Data Collection AF.
type DataCollectionClientType struct {
	union json.RawMessage
}

// DataCollectionClientType0 defines model for DataCollectionClientType.0.
type DataCollectionClientType0 string

// DataCollectionClientType1 This string provides forward-compatibility with future extensions to the enumeration but is not used to encode content defined in the present version of this API.
type DataCollectionClientType1 = string

// DataReportingRule Instructions on how collected UE data is to be reported by the data collection client to the Data Collection AF.
type DataReportingRule struct {
	DataPackagingStrategy *string `json:"dataPackagingStrategy,omitempty"`

	// ReportingFormat String providing an URI formatted according to RFC 3986.
	ReportingFormat      Uri         `json:"reportingFormat"`
	ReportingProbability *Percentage `json:"reportingProbability,omitempty"`
}

// DataSamplingRule Instructions on how UE data is to be sampled by the data collection client.
type DataSamplingRule struct {
	// LocationFilter Represents a user location area when the UE is attached to 5G.
	LocationFilter *LocationArea5G `json:"locationFilter,omitempty"`

	// SamplingPeriod string with format 'float' as defined in OpenAPI.
	SamplingPeriod *Float `json:"samplingPeriod,omitempty"`
}

// AsDataCollectionClientType0 returns the union data inside the DataCollectionClientType as a DataCollectionClientType0
func (t DataCollectionClientType) AsDataCollectionClientType0() (DataCollectionClientType0, error) {
	var body DataCollectionClientType0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDataCollectionClientType0 overwrites any union data inside the DataCollectionClientType as the provided DataCollectionClientType0
func (t *DataCollectionClientType) FromDataCollectionClientType0(v DataCollectionClientType0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDataCollectionClientType0 performs a merge with any union data inside the DataCollectionClientType, using the provided DataCollectionClientType0
func (t *DataCollectionClientType) MergeDataCollectionClientType0(v DataCollectionClientType0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDataCollectionClientType1 returns the union data inside the DataCollectionClientType as a DataCollectionClientType1
func (t DataCollectionClientType) AsDataCollectionClientType1() (DataCollectionClientType1, error) {
	var body DataCollectionClientType1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDataCollectionClientType1 overwrites any union data inside the DataCollectionClientType as the provided DataCollectionClientType1
func (t *DataCollectionClientType) FromDataCollectionClientType1(v DataCollectionClientType1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDataCollectionClientType1 performs a merge with any union data inside the DataCollectionClientType, using the provided DataCollectionClientType1
func (t *DataCollectionClientType) MergeDataCollectionClientType1(v DataCollectionClientType1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DataCollectionClientType) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DataCollectionClientType) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
