// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package gppmodel

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AdrfDataType0.
const (
	AdrfDataType0HISTORICALANALYTICS AdrfDataType0 = "HISTORICAL_ANALYTICS"
	AdrfDataType0HISTORICALDATA      AdrfDataType0 = "HISTORICAL_DATA"
)

// Valid indicates whether the value is a known member of the AdrfDataType0 enum.
func (e AdrfDataType0) Valid() bool {
	switch e {
	case AdrfDataType0HISTORICALANALYTICS:
		return true
	case AdrfDataType0HISTORICALDATA:
		return true
	default:
		return false
	}
}

// Defines values for ContextType0.
const (
	ContextType0AGGRINFO            ContextType0 = "AGGR_INFO"
	ContextType0AGGRSUBS            ContextType0 = "AGGR_SUBS"
	ContextType0ANALYTICSACCUINFO   ContextType0 = "ANALYTICS_ACCU_INFO"
	ContextType0DATA                ContextType0 = "DATA"
	ContextType0HISTORICALANALYTICS ContextType0 = "HISTORICAL_ANALYTICS"
	ContextType0MLMODELACCUINFO     ContextType0 = "ML_MODEL_ACCU_INFO"
	ContextType0MLMODELS            ContextType0 = "ML_MODELS"
	ContextType0PENDINGANALYTICS    ContextType0 = "PENDING_ANALYTICS"
)

// Valid indicates whether the value is a known member of the ContextType0 enum.
func (e ContextType0) Valid() bool {
	switch e {
	case ContextType0AGGRINFO:
		return true
	case ContextType0AGGRSUBS:
		return true
	case ContextType0ANALYTICSACCUINFO:
		return true
	case ContextType0DATA:
		return true
	case ContextType0HISTORICALANALYTICS:
		return true
	case ContextType0MLMODELACCUINFO:
		return true
	case ContextType0MLMODELS:
		return true
	case ContextType0PENDINGANALYTICS:
		return true
	default:
		return false
	}
}

// Defines values for EventId0.
const (
	EventId0ABNORMALBEHAVIOUR    EventId0 = "ABNORMAL_BEHAVIOUR"
	EventId0DISPERSION           EventId0 = "DISPERSION"
	EventId0DNPERFORMANCE        EventId0 = "DN_PERFORMANCE"
	EventId0E2EDATAVOLTRANSTIME  EventId0 = "E2E_DATA_VOL_TRANS_TIME"
	EventId0LOADLEVELINFORMATION EventId0 = "LOAD_LEVEL_INFORMATION"
	EventId0LOCACCURACY          EventId0 = "LOC_ACCURACY"
	EventId0MOVEMENTBEHAVIOUR    EventId0 = "MOVEMENT_BEHAVIOUR"
	EventId0NETWORKPERFORMANCE   EventId0 = "NETWORK_PERFORMANCE"
	EventId0NFLOAD               EventId0 = "NF_LOAD"
	EventId0NSILOADLEVEL         EventId0 = "NSI_LOAD_LEVEL"
	EventId0PDUSESSIONTRAFFIC    EventId0 = "PDU_SESSION_TRAFFIC"
	EventId0PFDDETERMINATION     EventId0 = "PFD_DETERMINATION"
	EventId0QOSSUSTAINABILITY    EventId0 = "QOS_SUSTAINABILITY"
	EventId0REDTRANSEXP          EventId0 = "RED_TRANS_EXP"
	EventId0RELATIVEPROXIMITY    EventId0 = "RELATIVE_PROXIMITY"
	EventId0SERVICEEXPERIENCE    EventId0 = "SERVICE_EXPERIENCE"
	EventId0SMCONGESTION         EventId0 = "SM_CONGESTION"
	EventId0UECOMMUNICATION      EventId0 = "UE_COMMUNICATION"
	EventId0UEMOBILITY           EventId0 = "UE_MOBILITY"
	EventId0USERDATACONGESTION   EventId0 = "USER_DATA_CONGESTION"
	EventId0WLANPERFORMANCE      EventId0 = "WLAN_PERFORMANCE"
)

// Valid indicates whether the value is a known member of the EventId0 enum.
func (e EventId0) Valid() bool {
	switch e {
	case EventId0ABNORMALBEHAVIOUR:
		return true
	case EventId0DISPERSION:
		return true
	case EventId0DNPERFORMANCE:
		return true
	case EventId0E2EDATAVOLTRANSTIME:
		return true
	case EventId0LOADLEVELINFORMATION:
		return true
	case EventId0LOCACCURACY:
		return true
	case EventId0MOVEMENTBEHAVIOUR:
		return true
	case EventId0NETWORKPERFORMANCE:
		return true
	case EventId0NFLOAD:
		return true
	case EventId0NSILOADLEVEL:
		return true
	case EventId0PDUSESSIONTRAFFIC:
		return true
	case EventId0PFDDETERMINATION:
		return true
	case EventId0QOSSUSTAINABILITY:
		return true
	case EventId0REDTRANSEXP:
		return true
	case EventId0RELATIVEPROXIMITY:
		return true
	case EventId0SERVICEEXPERIENCE:
		return true
	case EventId0SMCONGESTION:
		return true
	case EventId0UECOMMUNICATION:
		return true
	case EventId0UEMOBILITY:
		return true
	case EventId0USERDATACONGESTION:
		return true
	case EventId0WLANPERFORMANCE:
		return true
	default:
		return false
	}
}

// AdditionInfoAnalyticsInfoRequest Indicates additional information why the analytics request is rejected.
type AdditionInfoAnalyticsInfoRequest struct {
	// RvWaitTime indicating a time in seconds.
	RvWaitTime *DurationSec `json:"rvWaitTime,omitempty"`
}

// AdrfDataType Represents a type of data that is stored in the ADRF.
// Possible values are:
// - HISTORICAL_ANALYTICS: Indicates that historical analytics are stored in the ADRF.
// - HISTORICAL_DATA: Indicates that historical data are stored in the ADRF.
type AdrfDataType struct {
	union json.RawMessage
}

// AdrfDataType0 defines model for AdrfDataType.0.
type AdrfDataType0 string

// AdrfDataType1 This string provides forward-compatibility with future extensions to the enumeration but is not used to encode content defined in the present version of this API.
type AdrfDataType1 = string

// AnalyticsAccuracyInfo Analytics Accuracy related information needs to be transferred.
type AnalyticsAccuracyInfo struct {
	// GroundTruthInfo The ground truth information used for the accuracy information computation.
	GroundTruthInfo *GroundTruthInfo `json:"groundTruthInfo,omitempty"`

	// PauseInd Indicates whether the analytics subscription has been paused. Set to "true" if it has been paused, otherwise set to "false".
	PauseInd *bool `json:"pauseInd,omitempty"`

	// RemainTimeWin Represents a time window identified by a start time and a stop time.
	RemainTimeWin *TimeWindow `json:"remainTimeWin,omitempty"`

	// ReportTime string with format 'date-time' as defined in OpenAPI.
	ReportTime *DateTime `json:"reportTime,omitempty"`
}

// AnalyticsData Represents the description of analytics with parameters as relevant for the requesting NF service consumer.
type AnalyticsData struct {
	AbnorBehavrs *[]AbnormalBehaviour `json:"abnorBehavrs,omitempty"`

	// AccuInfo The analytics accuracy information.
	AccuInfo *AccuracyInfo `json:"accuInfo,omitempty"`

	// AnaMetaInfo Contains analytics metadata information required for analytics aggregation.
	AnaMetaInfo *AnalyticsMetadataInfo `json:"anaMetaInfo,omitempty"`

	// CancelAccuInd Indicates cancelled request of the analytics accuracy information. Set to "true" indicates the NWDAF cancelled request of analytics accuracy information as the NWDAF does not support the accuracy checking capability. Otherwise set to "false". Default value is "false" if omitted.
	CancelAccuInd     *bool                      `json:"cancelAccuInd,omitempty"`
	DataVlTrnsTmInfos *[]E2eDataVolTransTimeInfo `json:"dataVlTrnsTmInfos,omitempty"`
	DisperInfos       *[]DispersionInfo          `json:"disperInfos,omitempty"`
	DnPerfInfos       *[]DnPerfInfo              `json:"dnPerfInfos,omitempty"`

	// Expiry string with format 'date-time' as defined in OpenAPI.
	Expiry            *DateTime                       `json:"expiry,omitempty"`
	LocAccInfos       *[]LocAccuracyInfo              `json:"locAccInfos,omitempty"`
	MovBehavInfos     *[]MovBehavInfo                 `json:"movBehavInfos,omitempty"`
	NfLoadLevelInfos  *[]NfLoadLevelInformation       `json:"nfLoadLevelInfos,omitempty"`
	NsiLoadLevelInfos *[]NsiLoadLevelInfo             `json:"nsiLoadLevelInfos,omitempty"`
	NwPerfs           *[]NetworkPerfInfo              `json:"nwPerfs,omitempty"`
	PduSesTrafInfos   *[]PduSesTrafficInfo            `json:"pduSesTrafInfos,omitempty"`
	QosSustainInfos   *[]QosSustainabilityInfo        `json:"qosSustainInfos,omitempty"`
	RedTransInfos     *[]RedundantTransmissionExpInfo `json:"redTransInfos,omitempty"`
	RelProxInfos      *[]RelProxInfo                  `json:"relProxInfos,omitempty"`

	// SliceLoadLevelInfos The slices and their load level information.
	SliceLoadLevelInfos *[]SliceLoadLevelInformation `json:"sliceLoadLevelInfos,omitempty"`
	SmccExps            *[]SmcceInfo                 `json:"smccExps,omitempty"`

	// Start string with format 'date-time' as defined in OpenAPI.
	Start *DateTime `json:"start,omitempty"`

	// SuppFeat A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of "0" to "9",  "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
	SuppFeat *SupportedFeatures       `json:"suppFeat,omitempty"`
	SvcExps  *[]ServiceExperienceInfo `json:"svcExps,omitempty"`

	// TimeStampGen string with format 'date-time' as defined in OpenAPI.
	TimeStampGen      *DateTime                 `json:"timeStampGen,omitempty"`
	UeComms           *[]UeCommunication        `json:"ueComms,omitempty"`
	UeMobs            *[]UeMobility             `json:"ueMobs,omitempty"`
	UserDataCongInfos *[]UserDataCongestionInfo `json:"userDataCongInfos,omitempty"`
	WlanInfos         *[]WlanPerformanceInfo    `json:"wlanInfos,omitempty"`
}

// ContextData Contains context information related to analytics subscriptions corresponding with one or more context identifiers.
type ContextData struct {
	// ContextElems List of items that contain context information corresponding with a context identifier.
	ContextElems []ContextElement `json:"contextElems"`
}

// ContextElement Contains context information corresponding with a specific context identifier.
type ContextElement struct {
	// AdrfDataTypes Type(s) of data stored in the ADRF by the NWDAF.
	AdrfDataTypes *[]AdrfDataType `json:"adrfDataTypes,omitempty"`

	// AdrfId String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.
	AdrfId *NfInstanceId `json:"adrfId,omitempty"`

	// AggrNwdafIds NWDAF identifiers of NWDAF instances used by the NWDAF service consumer when aggregating multiple analytics subscriptions.
	AggrNwdafIds *[]NfInstanceId `json:"aggrNwdafIds,omitempty"`

	// AggrSubs Information about analytics subscriptions that the NWDAF has with other NWDAFs to perform aggregation.
	AggrSubs *[]SpecificAnalyticsSubscription `json:"aggrSubs,omitempty"`

	// AnaAccuInfos The Analytics Accuracy related information.
	AnaAccuInfos *[]AnalyticsAccuracyInfo `json:"anaAccuInfos,omitempty"`

	// ContextId Contains information about available analytics contexts.
	ContextId AnalyticsContextIdentifier `json:"contextId"`

	// HistAnalytics Historical output analytics.
	HistAnalytics *[]EventNotification `json:"histAnalytics,omitempty"`

	// HistData Historical data related to the analytics subscription.
	HistData *[]HistoricalData `json:"histData,omitempty"`

	// LastOutputTime string with format 'date-time' as defined in OpenAPI.
	LastOutputTime *DateTime `json:"lastOutputTime,omitempty"`

	// ModelAccuInfos The ML Model accuracy related information.
	ModelAccuInfos *[]MlModelAccuracyInfo `json:"modelAccuInfos,omitempty"`

	// ModelInfo Contains information identifying the ML model(s) that the consumer NWDAF is currently subscribing for the analytics.
	ModelInfo *[]ModelInfo `json:"modelInfo,omitempty"`

	// PendAnalytics Output analytics for the analytics subscription which have not yet been sent to the analytics consumer.
	PendAnalytics *[]EventNotification `json:"pendAnalytics,omitempty"`
}

// ContextIdList Contains a list of context identifiers of context information of analytics subscriptions.
type ContextIdList struct {
	ContextIds []AnalyticsContextIdentifier `json:"contextIds"`
}

// ContextType Represents the analytics context information type.
// Possible values are:
//   - PENDING_ANALYTICS: Represents context information that relates to pending output
//     analytics.
//   - HISTORICAL_ANALYTICS: Represents context information that relates to historical output
//     analytics.
//   - AGGR_SUBS: Represents context information about the analytics subscriptions that an NWDAF
//     has with other NWDAFs that collectively serve an analytics subscription.
//   - DATA: Represents context information about historical data that is available.
//   - AGGR_INFO: Represents context information that is related to aggregation of analytics
//     from multiple NWDAF subscriptions.
//   - ML_MODELS: Represents context information about used ML models.
//   - ANALYTICS_ACCU_INFO: Represents the Analytics Accuracy related information.
//   - ML_MODEL_ACCU_INFO: Represents the ML Model accuracy related information.
type ContextType struct {
	union json.RawMessage
}

// ContextType0 defines model for ContextType.0.
type ContextType0 string

// ContextType1 This string provides forward-compatibility with future extensions to the enumeration but is not used to encode content defined in the present version of this API.
type ContextType1 = string

// EventFilter Represents the event filters used to identify the requested analytics.
type EventFilter struct {
	// AccuReq Represents the analytics accuracy requirement information.
	AccuReq       *AccuracyReq                      `json:"accuReq,omitempty"`
	AddNwPerfReqs *[]ResourceUsageRequPerNwPerfType `json:"addNwPerfReqs,omitempty"`

	// AnySlice "false" represents not applicable for all slices. "true" represents applicable for all slices.
	AnySlice        *AnySlice                 `json:"anySlice,omitempty"`
	AppIds          *[]ApplicationId          `json:"appIds,omitempty"`
	AppServerAddrs  *[]AddrFqdn               `json:"appServerAddrs,omitempty"`
	BwRequs         *[]BwRequirement          `json:"bwRequs,omitempty"`
	DataVlTrnsTmRqs *[]E2eDataVolTransTimeReq `json:"dataVlTrnsTmRqs,omitempty"`
	DisperReqs      *[]DispersionRequirement  `json:"disperReqs,omitempty"`
	DnPerfReqs      *[]DnPerformanceReq       `json:"dnPerfReqs,omitempty"`
	Dnais           *[]Dnai                   `json:"dnais,omitempty"`
	Dnns            *[]Dnn                    `json:"dnns,omitempty"`
	ExcepIds        *[]ExceptionId            `json:"excepIds,omitempty"`

	// ExptAnaType Represents the expected UE analytics type.
	// Possible values are:
	// - MOBILITY: Mobility related abnormal behaviour analytics is expected by the consumer.
	// - COMMUN: Communication related abnormal behaviour analytics is expected by the consumer.
	// - MOBILITY_AND_COMMUN: Both mobility and communication related abnormal behaviour analytics
	//   is expected by the consumer.
	ExptAnaType *ExpectedAnalyticsType   `json:"exptAnaType,omitempty"`
	ExptUeBehav *ExpectedUeBehaviourData `json:"exptUeBehav,omitempty"`

	// FineGranAreas Indicates the fine granularity areas to which the request applies.
	FineGranAreas *[]GeographicalArea `json:"fineGranAreas,omitempty"`

	// LadnDnns Identification(s) of LADN DNN to indicate the LADN service area as the AOI.
	LadnDnns         *[]Dnn             `json:"ladnDnns,omitempty"`
	ListOfAnaSubsets *[]AnalyticsSubset `json:"listOfAnaSubsets,omitempty"`
	LocAccReqs       *[]LocAccuracyReq  `json:"locAccReqs,omitempty"`

	// LocGranularity Represents the preferred granularity of location information.
	// Possible values are:
	//   - TA_LEVEL: Indicates location granularity of TA level.
	//   - CELL_LEVEL: Indicates location granularity of Cell level.
	//   - LON_AND_LAT_LEVEL: Indicates location granularity of longitude and latitude level.
	LocGranularity *LocInfoGranularity `json:"locGranularity,omitempty"`

	// LocOrientation Possible values are:
	//   - HORIZONTAL: Indicates horizontal orientation.
	//   - VERTICAL: Indicates vertical orientation.
	//   - HOR_AND_VER: Indicates both horizontal and vertical orientation.
	LocOrientation *LocationOrientation `json:"locOrientation,omitempty"`

	// Location Represents a horizontal and optionally vertical location using either geographic or local coordinates.
	Location *GeoLocation `json:"location,omitempty"`

	// MaxTopAppDlNbr Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	MaxTopAppDlNbr *Uinteger `json:"maxTopAppDlNbr,omitempty"`

	// MaxTopAppUlNbr Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	MaxTopAppUlNbr *Uinteger      `json:"maxTopAppUlNbr,omitempty"`
	MovBehavReqs   *[]MovBehavReq `json:"movBehavReqs,omitempty"`

	// NetworkArea Describes a network area information in which the NF service consumer requests the number of UEs.
	NetworkArea    *NetworkAreaInfo    `json:"networkArea,omitempty"`
	NfInstanceIds  *[]NfInstanceId     `json:"nfInstanceIds,omitempty"`
	NfSetIds       *[]NfSetId          `json:"nfSetIds,omitempty"`
	NfTypes        *[]NFType           `json:"nfTypes,omitempty"`
	NsiIdInfos     *[]NsiIdInfo        `json:"nsiIdInfos,omitempty"`
	NwPerfReqs     *[]NetworkPerfReq   `json:"nwPerfReqs,omitempty"`
	NwPerfTypes    *[]NetworkPerfType  `json:"nwPerfTypes,omitempty"`
	PduSesInfos    *[]NwdafPduSessionInfo `json:"pduSesInfos,omitempty"`
	PduSesTrafReqs *[]PduSesTrafficReq `json:"pduSesTrafReqs,omitempty"`

	// QosRequ Represents the QoS requirements.
	QosRequ      *QosRequirement                `json:"qosRequ,omitempty"`
	RatFreqs     *[]RatFreqInformation          `json:"ratFreqs,omitempty"`
	RedTransReqs *[]RedundantTransmissionExpReq `json:"redTransReqs,omitempty"`
	RelProxReqs  *[]RelProxReq                  `json:"relProxReqs,omitempty"`

	// RoamingInfo Information related to roaming analytics.
	RoamingInfo *RoamingInfo `json:"roamingInfo,omitempty"`

	// Snssais Identification(s) of network slice.
	Snssais *[]Snssai `json:"snssais,omitempty"`

	// SpatialGranSizeCell Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	SpatialGranSizeCell *Uinteger `json:"spatialGranSizeCell,omitempty"`

	// SpatialGranSizeTa Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	SpatialGranSizeTa *Uinteger `json:"spatialGranSizeTa,omitempty"`

	// TemporalGranSize indicating a time in seconds.
	TemporalGranSize *DurationSec     `json:"temporalGranSize,omitempty"`
	UeCommReqs       *[]UeCommReq     `json:"ueCommReqs,omitempty"`
	UeMobilityReqs   *[]UeMobilityReq `json:"ueMobilityReqs,omitempty"`

	// UpfInfo Represents the ID/address/FQDN of the UPF.
	UpfInfo *UpfInformation `json:"upfInfo,omitempty"`

	// UseCaseCxt Indicates the context of usage of the analytics. The value and format of this parameter are not standardized.
	UseCaseCxt      *string               `json:"useCaseCxt,omitempty"`
	UserDataConReqs *[]UserDataCongestReq `json:"userDataConReqs,omitempty"`
	VisitedAreas    *[]NetworkAreaInfo    `json:"visitedAreas,omitempty"`
	WlanReqs        *[]WlanPerformanceReq `json:"wlanReqs,omitempty"`
}

// EventId Represents the analytics type.
// Possible values are:
//   - LOAD_LEVEL_INFORMATION: Represent the analytics of load level information of corresponding
//     network slice.
//   - NETWORK_PERFORMANCE: Represent the analytics of network performance information.
//   - NF_LOAD: Indicates that the event subscribed is NF Load.
//   - SERVICE_EXPERIENCE: Represent the analytics of service experience information of the
//     specific applications.
//   - UE_MOBILITY: Represent the analytics of UE mobility.
//   - UE_COMMUNICATION: Represent the analytics of UE communication.
//   - QOS_SUSTAINABILITY: Represent the analytics of QoS sustainability information in the
//     certain area.
//   - ABNORMAL_BEHAVIOUR: Indicates that the event subscribed is abnormal behaviour information.
//   - USER_DATA_CONGESTION: Represent the analytics of the user data congestion in the certain
//     area.
//   - NSI_LOAD_LEVEL: Represent the analytics of Network Slice and the optionally associated
//     Network Slice Instance.
//   - SM_CONGESTION: Represent the analytics of Session Management congestion control experience
//     information for specific DNN and/or S-NSSAI.
//   - DISPERSION: Represents the analytics of dispersion.
//   - RED_TRANS_EXP: Represents the analytics of Redundant Transmission Experience.
//   - WLAN_PERFORMANCE: Represents the analytics of WLAN performance.
//   - DN_PERFORMANCE: Represents the analytics of DN performance.
//   - PFD_DETERMINATION: Represents the analytics of PFD Determination information for known application identifier(s).
//   - PDU_SESSION_TRAFFIC: Represents the analytics of PDU Session traffic.
//   - E2E_DATA_VOL_TRANS_TIME: Represents the analytics of E2E data volume transfer time.
//   - MOVEMENT_BEHAVIOUR: Represents the analytics of the Movement Behaviour information.
//   - LOC_ACCURACY: Represents the analytics of location accuracy.
//   - RELATIVE_PROXIMITY: Represents the analytics of Relative Proximity information.
type EventId struct {
	union json.RawMessage
}

// EventId0 defines model for EventId.0.
type EventId0 string

// EventId1 This string provides forward-compatibility with future extensions to the enumeration but is not used to encode content defined in the present version of this API.
type EventId1 = string

// GroundTruthInfo The ground truth information used for the accuracy information computation.
type GroundTruthInfo struct {
	// AnalyticsId Represents the analytics type.
	// Possible values are:
	// - LOAD_LEVEL_INFORMATION: Represent the analytics of load level information of corresponding
	//   network slice.
	// - NETWORK_PERFORMANCE: Represent the analytics of network performance information.
	// - NF_LOAD: Indicates that the event subscribed is NF Load.
	// - SERVICE_EXPERIENCE: Represent the analytics of service experience information of the
	//   specific applications.
	// - UE_MOBILITY: Represent the analytics of UE mobility.
	// - UE_COMMUNICATION: Represent the analytics of UE communication.
	// - QOS_SUSTAINABILITY: Represent the analytics of QoS sustainability information in the
	//   certain area.
	// - ABNORMAL_BEHAVIOUR: Indicates that the event subscribed is abnormal behaviour information.
	// - USER_DATA_CONGESTION: Represent the analytics of the user data congestion in the certain
	//   area.
	// - NSI_LOAD_LEVEL: Represent the analytics of Network Slice and the optionally associated
	//   Network Slice Instance.
	// - SM_CONGESTION: Represent the analytics of Session Management congestion control experience
	//   information for specific DNN and/or S-NSSAI.
	// - DISPERSION: Represents the analytics of dispersion.
	// - RED_TRANS_EXP: Represents the analytics of Redundant Transmission Experience.
	// - WLAN_PERFORMANCE: Represents the analytics of WLAN performance.
	// - DN_PERFORMANCE: Represents the analytics of DN performance.
	// - PFD_DETERMINATION: Represents the analytics of PFD Determination information for known application identifier(s).
	// - PDU_SESSION_TRAFFIC: Represents the analytics of PDU Session traffic.
	// - E2E_DATA_VOL_TRANS_TIME: Represents the analytics of E2E data volume transfer time.
	// - MOVEMENT_BEHAVIOUR: Represents the analytics of the Movement Behaviour information.
	// - LOC_ACCURACY: Represents the analytics of location accuracy.
	// - RELATIVE_PROXIMITY: Represents the analytics of Relative Proximity information.
	AnalyticsId EventId `json:"analyticsId"`

	// DataSourceIds The NF instance ID(s) of the data source for ground truth data.
	DataSourceIds *[]NfInstanceId `json:"dataSourceIds,omitempty"`

	// DataSourceSetIds The NF Set ID(s) of the data source for ground truth data.
	DataSourceSetIds *[]NfSetId `json:"dataSourceSetIds,omitempty"`

	// DataSub Contains a data specification.
	DataSub *DataSubscription `json:"dataSub,omitempty"`

	// GroundTruthData The ground truth information.
	GroundTruthData *string `json:"groundTruthData,omitempty"`
}

// HistoricalData Contains historical data related to an analytics subscription.
type HistoricalData struct {
	// Data Historical data related to the analytics.
	Data []DataNotification `json:"data"`

	// EndTime string with format 'date-time' as defined in OpenAPI.
	EndTime *DateTime `json:"endTime,omitempty"`

	// StartTime string with format 'date-time' as defined in OpenAPI.
	StartTime *DateTime `json:"startTime,omitempty"`

	// SubsWithSources Information about subscriptions with the data sources.
	SubsWithSources *[]SpecificDataSubscription `json:"subsWithSources,omitempty"`
}

// MlModelAccuracyInfo The ML Model Accuracy Subscription Information needs to be transferred.
type MlModelAccuracyInfo struct {
	// AccuSubInfo Extended parameters for ML model provisioning which can optionally be set by a service consuumer NF.
	AccuSubInfo *ModelProvisionParamsExt `json:"accuSubInfo,omitempty"`

	// SourceId String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.
	SourceId *NfInstanceId `json:"sourceId,omitempty"`

	// SourceSetId NF Set Identifier (see clause 28.12 of 3GPP TS 23.003), formatted as the following string "set<Set ID>.<nftype>set.5gc.mnc<MNC>.mcc<MCC>", or  "set<SetID>.<NFType>set.5gc.nid<NID>.mnc<MNC>.mcc<MCC>" with  <MCC> encoded as defined in clause 5.4.2 ("Mcc" data type definition)  <MNC> encoding the Mobile Network Code part of the PLMN, comprising 3 digits.
	//   If there are only 2 significant digits in the MNC, one "0" digit shall be inserted
	//   at the left side to fill the 3 digits coding of MNC.  Pattern: '^[0-9]{3}$'
	// <NFType> encoded as a value defined in Table 6.1.6.3.3-1 of 3GPP TS 29.510 but
	//   with lower case characters <Set ID> encoded as a string of characters consisting of
	//   alphabetic characters (A-Z and a-z), digits (0-9) and/or the hyphen (-) and that
	//   shall end with either an alphabetic character or a digit.
	SourceSetId *NfSetId `json:"sourceSetId,omitempty"`

	// SubscriptionId The identifier of the subscription for the ML Model accuracy information.
	SubscriptionId string `json:"subscriptionId"`
}

// NetworkPerfReq Represents a network performance requirement.
type NetworkPerfReq struct {
	// OrderCriterion Represents the ordering criterion for the list of network performance analytics.
	// Possible values are:
	//   - NUMBER_OF_UES: The ordering criterion of the analytics is the number of UEs.
	//   - COMMUNICATION_PERF: The ordering criterion of the analytics is the communication performance.
	//   - MOBILITY_PERF: The ordering criterion of the analytics is themobility performance.
	OrderCriterion *NetworkPerfOrderCriterion `json:"orderCriterion,omitempty"`

	// OrderDirection Represents the matching direction when crossing a threshold.
	// Possible values are:
	// - ASCENDING: Threshold is crossed in ascending direction.
	// - DESCENDING: Threshold is crossed in descending direction.
	// - CROSSED: Threshold is crossed either in ascending or descending direction.
	OrderDirection *MatchingDirection `json:"orderDirection,omitempty"`
}

// ProblemDetailsAnalyticsInfoRequest defines model for ProblemDetailsAnalyticsInfoRequest.
type ProblemDetailsAnalyticsInfoRequest struct {
	// AccessTokenError Error returned in the access token response message
	AccessTokenError *AccessTokenErr `json:"accessTokenError,omitempty"`

	// AccessTokenRequest Contains information related to the access token request
	AccessTokenRequest *AccessTokenReq `json:"accessTokenRequest,omitempty"`

	// Cause A machine-readable application error cause specific to this occurrence of the problem.  This IE should be present and provide application-related error information, if available.
	Cause *string `json:"cause,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Instance String providing an URI formatted according to RFC 3986.
	Instance      *Uri            `json:"instance,omitempty"`
	InvalidParams *[]InvalidParam `json:"invalidParams,omitempty"`

	// NoProfileMatchInfo Provides the reason for not finding NF matching the search criteria
	NoProfileMatchInfo *NoProfileMatchInfo `json:"noProfileMatchInfo,omitempty"`

	// NrfId Fully Qualified Domain Name
	NrfId *Fqdn `json:"nrfId,omitempty"`

	// RvWaitTime indicating a time in seconds.
	RvWaitTime           *DurationSec `json:"rvWaitTime,omitempty"`
	Status               *int         `json:"status,omitempty"`
	SupportedApiVersions *[]string    `json:"supportedApiVersions,omitempty"`

	// SupportedFeatures A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of "0" to "9",  "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
	SupportedFeatures *SupportedFeatures `json:"supportedFeatures,omitempty"`
	Title             *string            `json:"title,omitempty"`

	// Type String providing an URI formatted according to RFC 3986.
	Type *Uri `json:"type,omitempty"`
}

// RequestedContext Contains types of analytics context information.
type RequestedContext struct {
	// Contexts List of analytics context types.
	Contexts []ContextType `json:"contexts"`

	// NfConsumerInfo Vendor ID of the NF Service instance (Private Enterprise Number assigned by IANA)
	NfConsumerInfo *VendorId `json:"nfConsumerInfo,omitempty"`
}

// ResourceUsageRequPerNwPerfType More requirement for each network performance type.
type ResourceUsageRequPerNwPerfType struct {
	// NwPerfType Represents the network performance types.
	// Possible values are:
	// - GNB_ACTIVE_RATIO: Indicates that the network performance requirement is gNodeB active
	//   (i.e. up and running) rate. Indicates the ratio of gNB active (i.e. up and running) number
	//   to the total number of gNB.
	// - GNB_COMPUTING_USAGE: Indicates gNodeB computing resource usage.
	// - GNB_MEMORY_USAGE: Indicates gNodeB memory usage.
	// - GNB_DISK_USAGE: Indicates gNodeB disk usage.
	// - GNB_RSC_USAGE_OVERALL_TRAFFIC: The gNB resource usage.
	// - GNB_RSC_USAGE_GBR_TRAFFIC: The gNB resource usage for GBR traffic.
	// - GNB_RSC_USAGE_DELAY_CRIT_GBR_TRAFFIC: The gNB resource usage for Delay-critical GBR
	//   traffic.
	// - NUM_OF_UE: Indicates number of UEs.
	// - SESS_SUCC_RATIO: Indicates ratio of successful setup of PDU sessions to total PDU
	//   session setup attempts.
	// - HO_SUCC_RATIO: Indicates Ratio of successful handovers to the total handover attempts.
	NwPerfType NetworkPerfType `json:"nwPerfType"`

	// RscUsgReq resource usage requirement.
	RscUsgReq *ResourceUsageRequirement `json:"rscUsgReq,omitempty"`
}

// SmcceInfo Represents the Session Management congestion control experience information.
type SmcceInfo struct {
	// Dnn String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. "Label1.Label2.Label3").
	Dnn *Dnn `json:"dnn,omitempty"`

	// SmcceUeList Represents the List of UEs classified based on experience level of Session Management congestion control.
	SmcceUeList SmcceUeList `json:"smcceUeList"`

	// Snssai When Snssai needs to be converted to string (e.g. when used in maps as key), the string shall be composed of one to three digits "sst" optionally followed by "-" and 6 hexadecimal digits "sd".
	Snssai *Snssai `json:"snssai,omitempty"`
}

// SmcceUeList Represents the List of UEs classified based on experience level of Session Management congestion control.
type SmcceUeList struct {
	HighLevel   *[]Supi `json:"highLevel,omitempty"`
	LowLevel    *[]Supi `json:"lowLevel,omitempty"`
	MediumLevel *[]Supi `json:"mediumLevel,omitempty"`
	union       json.RawMessage
}

// SmcceUeList0 defines model for .
type SmcceUeList0 = interface{}

// SmcceUeList1 defines model for .
type SmcceUeList1 = interface{}

// SmcceUeList2 defines model for .
type SmcceUeList2 = interface{}

// SpecificAnalyticsSubscription defines model for SpecificAnalyticsSubscription.
type SpecificAnalyticsSubscription struct {
	union json.RawMessage
}

// SpecificAnalyticsSubscription0 defines model for .
type SpecificAnalyticsSubscription0 = interface{}

// SpecificAnalyticsSubscription1 defines model for .
type SpecificAnalyticsSubscription1 = interface{}

// SpecificDataSubscription defines model for SpecificDataSubscription.
type SpecificDataSubscription struct {
	union json.RawMessage
}

// SpecificDataSubscription0 defines model for .
type SpecificDataSubscription0 = interface{}

// SpecificDataSubscription1 defines model for .
type SpecificDataSubscription1 = interface{}

// UserDataCongestReq Represents a user data congesion requirement.
type UserDataCongestReq struct {
	// OrderCriterion Represents the cause for requesting to terminate an analytics subscription.
	// Possible values are:
	//   - APPLICABLE_TIME_WINDOW: The ordering criterion is the Applicable Time Window.
	//   - NETWORK_STATUS_INDICATION: The ordering criterion is the network status indication.
	OrderCriterion *UserDataConOrderCrit `json:"orderCriterion,omitempty"`

	// OrderDirection Represents the matching direction when crossing a threshold.
	// Possible values are:
	// - ASCENDING: Threshold is crossed in ascending direction.
	// - DESCENDING: Threshold is crossed in descending direction.
	// - CROSSED: Threshold is crossed either in ascending or descending direction.
	OrderDirection *MatchingDirection `json:"orderDirection,omitempty"`
}

// GetNWDAFAnalyticsParams defines parameters for GetNWDAFAnalytics.
type GetNWDAFAnalyticsParams struct {
	// EventId Identify the analytics.
	EventId EventId `form:"event-id" json:"event-id"`

	// AnaReq Identifies the analytics reporting requirement information.
	AnaReq *EventReportingRequirement `form:"ana-req,omitempty" json:"ana-req,omitempty"`

	// EventFilter Identify the analytics.
	EventFilter *EventFilter `form:"event-filter,omitempty" json:"event-filter,omitempty"`

	// SupportedFeatures To filter irrelevant responses related to unsupported features.
	SupportedFeatures *SupportedFeatures `form:"supported-features,omitempty" json:"supported-features,omitempty"`

	// TgtUe Identify the target UE information.
	TgtUe *TargetUeInformation `form:"tgt-ue,omitempty" json:"tgt-ue,omitempty"`
}

// GetNwdafContextParams defines parameters for GetNwdafContext.
type GetNwdafContextParams struct {
	// ContextIds Identifies specific context information related to analytics subscriptions.
	ContextIds ContextIdList `form:"context-ids" json:"context-ids"`

	// ReqContext Identfies the type(s) of the analytics context information the consumer wishes to receive.
	ReqContext *RequestedContext `form:"req-context,omitempty" json:"req-context,omitempty"`
}

// AsAdrfDataType0 returns the union data inside the AdrfDataType as a AdrfDataType0
func (t AdrfDataType) AsAdrfDataType0() (AdrfDataType0, error) {
	var body AdrfDataType0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdrfDataType0 overwrites any union data inside the AdrfDataType as the provided AdrfDataType0
func (t *AdrfDataType) FromAdrfDataType0(v AdrfDataType0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdrfDataType0 performs a merge with any union data inside the AdrfDataType, using the provided AdrfDataType0
func (t *AdrfDataType) MergeAdrfDataType0(v AdrfDataType0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAdrfDataType1 returns the union data inside the AdrfDataType as a AdrfDataType1
func (t AdrfDataType) AsAdrfDataType1() (AdrfDataType1, error) {
	var body AdrfDataType1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdrfDataType1 overwrites any union data inside the AdrfDataType as the provided AdrfDataType1
func (t *AdrfDataType) FromAdrfDataType1(v AdrfDataType1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdrfDataType1 performs a merge with any union data inside the AdrfDataType, using the provided AdrfDataType1
func (t *AdrfDataType) MergeAdrfDataType1(v AdrfDataType1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AdrfDataType) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AdrfDataType) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsContextType0 returns the union data inside the ContextType as a ContextType0
func (t ContextType) AsContextType0() (ContextType0, error) {
	var body ContextType0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContextType0 overwrites any union data inside the ContextType as the provided ContextType0
func (t *ContextType) FromContextType0(v ContextType0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContextType0 performs a merge with any union data inside the ContextType, using the provided ContextType0
func (t *ContextType) MergeContextType0(v ContextType0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContextType1 returns the union data inside the ContextType as a ContextType1
func (t ContextType) AsContextType1() (ContextType1, error) {
	var body ContextType1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContextType1 overwrites any union data inside the ContextType as the provided ContextType1
func (t *ContextType) FromContextType1(v ContextType1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContextType1 performs a merge with any union data inside the ContextType, using the provided ContextType1
func (t *ContextType) MergeContextType1(v ContextType1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContextType) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContextType) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEventId0 returns the union data inside the EventId as a EventId0
func (t EventId) AsEventId0() (EventId0, error) {
	var body EventId0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventId0 overwrites any union data inside the EventId as the provided EventId0
func (t *EventId) FromEventId0(v EventId0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventId0 performs a merge with any union data inside the EventId, using the provided EventId0
func (t *EventId) MergeEventId0(v EventId0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventId1 returns the union data inside the EventId as a EventId1
func (t EventId) AsEventId1() (EventId1, error) {
	var body EventId1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventId1 overwrites any union data inside the EventId as the provided EventId1
func (t *EventId) FromEventId1(v EventId1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventId1 performs a merge with any union data inside the EventId, using the provided EventId1
func (t *EventId) MergeEventId1(v EventId1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EventId) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EventId) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSmcceUeList0 returns the union data inside the SmcceUeList as a SmcceUeList0
func (t SmcceUeList) AsSmcceUeList0() (SmcceUeList0, error) {
	var body SmcceUeList0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSmcceUeList0 overwrites any union data inside the SmcceUeList as the provided SmcceUeList0
func (t *SmcceUeList) FromSmcceUeList0(v SmcceUeList0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSmcceUeList0 performs a merge with any union data inside the SmcceUeList, using the provided SmcceUeList0
func (t *SmcceUeList) MergeSmcceUeList0(v SmcceUeList0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSmcceUeList1 returns the union data inside the SmcceUeList as a SmcceUeList1
func (t SmcceUeList) AsSmcceUeList1() (SmcceUeList1, error) {
	var body SmcceUeList1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSmcceUeList1 overwrites any union data inside the SmcceUeList as the provided SmcceUeList1
func (t *SmcceUeList) FromSmcceUeList1(v SmcceUeList1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSmcceUeList1 performs a merge with any union data inside the SmcceUeList, using the provided SmcceUeList1
func (t *SmcceUeList) MergeSmcceUeList1(v SmcceUeList1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSmcceUeList2 returns the union data inside the SmcceUeList as a SmcceUeList2
func (t SmcceUeList) AsSmcceUeList2() (SmcceUeList2, error) {
	var body SmcceUeList2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSmcceUeList2 overwrites any union data inside the SmcceUeList as the provided SmcceUeList2
func (t *SmcceUeList) FromSmcceUeList2(v SmcceUeList2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSmcceUeList2 performs a merge with any union data inside the SmcceUeList, using the provided SmcceUeList2
func (t *SmcceUeList) MergeSmcceUeList2(v SmcceUeList2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SmcceUeList) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.HighLevel != nil {
		object["highLevel"], err = json.Marshal(t.HighLevel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'highLevel': %w", err)
		}
	}

	if t.LowLevel != nil {
		object["lowLevel"], err = json.Marshal(t.LowLevel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lowLevel': %w", err)
		}
	}

	if t.MediumLevel != nil {
		object["mediumLevel"], err = json.Marshal(t.MediumLevel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mediumLevel': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *SmcceUeList) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["highLevel"]; found {
		err = json.Unmarshal(raw, &t.HighLevel)
		if err != nil {
			return fmt.Errorf("error reading 'highLevel': %w", err)
		}
	}

	if raw, found := object["lowLevel"]; found {
		err = json.Unmarshal(raw, &t.LowLevel)
		if err != nil {
			return fmt.Errorf("error reading 'lowLevel': %w", err)
		}
	}

	if raw, found := object["mediumLevel"]; found {
		err = json.Unmarshal(raw, &t.MediumLevel)
		if err != nil {
			return fmt.Errorf("error reading 'mediumLevel': %w", err)
		}
	}

	return err
}

// AsSpecificAnalyticsSubscription0 returns the union data inside the SpecificAnalyticsSubscription as a SpecificAnalyticsSubscription0
func (t SpecificAnalyticsSubscription) AsSpecificAnalyticsSubscription0() (SpecificAnalyticsSubscription0, error) {
	var body SpecificAnalyticsSubscription0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSpecificAnalyticsSubscription0 overwrites any union data inside the SpecificAnalyticsSubscription as the provided SpecificAnalyticsSubscription0
func (t *SpecificAnalyticsSubscription) FromSpecificAnalyticsSubscription0(v SpecificAnalyticsSubscription0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSpecificAnalyticsSubscription0 performs a merge with any union data inside the SpecificAnalyticsSubscription, using the provided SpecificAnalyticsSubscription0
func (t *SpecificAnalyticsSubscription) MergeSpecificAnalyticsSubscription0(v SpecificAnalyticsSubscription0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSpecificAnalyticsSubscription1 returns the union data inside the SpecificAnalyticsSubscription as a SpecificAnalyticsSubscription1
func (t SpecificAnalyticsSubscription) AsSpecificAnalyticsSubscription1() (SpecificAnalyticsSubscription1, error) {
	var body SpecificAnalyticsSubscription1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSpecificAnalyticsSubscription1 overwrites any union data inside the SpecificAnalyticsSubscription as the provided SpecificAnalyticsSubscription1
func (t *SpecificAnalyticsSubscription) FromSpecificAnalyticsSubscription1(v SpecificAnalyticsSubscription1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSpecificAnalyticsSubscription1 performs a merge with any union data inside the SpecificAnalyticsSubscription, using the provided SpecificAnalyticsSubscription1
func (t *SpecificAnalyticsSubscription) MergeSpecificAnalyticsSubscription1(v SpecificAnalyticsSubscription1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SpecificAnalyticsSubscription) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SpecificAnalyticsSubscription) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSpecificDataSubscription0 returns the union data inside the SpecificDataSubscription as a SpecificDataSubscription0
func (t SpecificDataSubscription) AsSpecificDataSubscription0() (SpecificDataSubscription0, error) {
	var body SpecificDataSubscription0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSpecificDataSubscription0 overwrites any union data inside the SpecificDataSubscription as the provided SpecificDataSubscription0
func (t *SpecificDataSubscription) FromSpecificDataSubscription0(v SpecificDataSubscription0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSpecificDataSubscription0 performs a merge with any union data inside the SpecificDataSubscription, using the provided SpecificDataSubscription0
func (t *SpecificDataSubscription) MergeSpecificDataSubscription0(v SpecificDataSubscription0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSpecificDataSubscription1 returns the union data inside the SpecificDataSubscription as a SpecificDataSubscription1
func (t SpecificDataSubscription) AsSpecificDataSubscription1() (SpecificDataSubscription1, error) {
	var body SpecificDataSubscription1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSpecificDataSubscription1 overwrites any union data inside the SpecificDataSubscription as the provided SpecificDataSubscription1
func (t *SpecificDataSubscription) FromSpecificDataSubscription1(v SpecificDataSubscription1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSpecificDataSubscription1 performs a merge with any union data inside the SpecificDataSubscription, using the provided SpecificDataSubscription1
func (t *SpecificDataSubscription) MergeSpecificDataSubscription1(v SpecificDataSubscription1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SpecificDataSubscription) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SpecificDataSubscription) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
