// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package gppmodel

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for Event0.
const (
	FAILEDRESOURCESALLOCATION     Event0 = "FAILED_RESOURCES_ALLOCATION"
	LOSSOFBEARER                  Event0 = "LOSS_OF_BEARER"
	RECOVERYOFBEARER              Event0 = "RECOVERY_OF_BEARER"
	RELEASEOFBEARER               Event0 = "RELEASE_OF_BEARER"
	SESSIONTERMINATION            Event0 = "SESSION_TERMINATION"
	SUCCESSFULRESOURCESALLOCATION Event0 = "SUCCESSFUL_RESOURCES_ALLOCATION"
	USAGEREPORT                   Event0 = "USAGE_REPORT"
)

// Valid indicates whether the value is a known member of the Event0 enum.
func (e Event0) Valid() bool {
	switch e {
	case FAILEDRESOURCESALLOCATION:
		return true
	case LOSSOFBEARER:
		return true
	case RECOVERYOFBEARER:
		return true
	case RELEASEOFBEARER:
		return true
	case SESSIONTERMINATION:
		return true
	case SUCCESSFULRESOURCESALLOCATION:
		return true
	case USAGEREPORT:
		return true
	default:
		return false
	}
}

// Defines values for ResultReason0.
const (
	OTHERREASON       ResultReason0 = "OTHER_REASON"
	ROAMINGNOTALLOWED ResultReason0 = "ROAMING_NOT_ALLOWED"
)

// Valid indicates whether the value is a known member of the ResultReason0 enum.
func (e ResultReason0) Valid() bool {
	switch e {
	case OTHERREASON:
		return true
	case ROAMINGNOTALLOWED:
		return true
	default:
		return false
	}
}

// AccumulatedUsage Represents an accumulated usage.
type AccumulatedUsage struct {
	// DownlinkVolume Unsigned integer identifying a volume in units of bytes.
	DownlinkVolume *Volume `json:"downlinkVolume,omitempty"`

	// Duration Unsigned integer identifying a period of time in units of seconds.
	Duration *DurationSec `json:"duration,omitempty"`

	// TotalVolume Unsigned integer identifying a volume in units of bytes.
	TotalVolume *Volume `json:"totalVolume,omitempty"`

	// UplinkVolume Unsigned integer identifying a volume in units of bytes.
	UplinkVolume *Volume `json:"uplinkVolume,omitempty"`
}

// Acknowledgement Represents a successful acknowledgement of a notification.
type Acknowledgement struct {
	// Details A human-readable explanation specific to this successful acknowledgement
	Details string `json:"details"`
}

// Bandwidth integer indicating a bandwidth in bits per second.
type Bandwidth = int

// BdtReferenceId string identifying a BDT Reference ID as defined in clause 5.3.3 of 3GPP TS 29.154.
type BdtReferenceId = string

// ConfigResult Represents one configuration processing result for a group's members.
type ConfigResult struct {
	// ExternalIds Each element indicates an external identifier of the UE.
	ExternalIds *[]ExternalId `json:"externalIds,omitempty"`

	// Msisdns Each element identifies the MS internal PSTN/ISDN number allocated for the UE.
	Msisdns *[]Msisdn `json:"msisdns,omitempty"`

	// ResultReason Represents a failure result reason.
	// Possible values are:
	// - ROAMING_NOT_ALLOWED: Identifies the configuration parameters are not allowed by roaming
	//   agreement.
	// - OTHER_REASON: Identifies the configuration parameters are not configured due to other
	//   reason.
	ResultReason ResultReason `json:"resultReason"`
	union        json.RawMessage
}

// ConfigResult0 defines model for .
type ConfigResult0 = interface{}

// ConfigResult1 defines model for .
type ConfigResult1 = interface{}

// DateTimeRo string with format "date-time" as defined in OpenAPI with "readOnly=true" property.
type DateTimeRo = time.Time

// DurationMin Unsigned integer identifying a period of time in units of minutes.
type DurationMin = int32

// DurationSecRo Unsigned integer identifying a period of time in units of seconds with "readOnly=true" property.
type DurationSecRo = int

// EthFlowInfo Represents Ethernet flow information.
type EthFlowInfo struct {
	// EthFlowDescriptions Indicates the packet filters of the Ethernet flow. It shall contain UL and/or DL Ethernet flow description.
	EthFlowDescriptions *[]EthFlowDescription `json:"ethFlowDescriptions,omitempty"`

	// FlowId Indicates the Ethernet flow identifier.
	FlowId int `json:"flowId"`
}

// Event Represents the event reported by the SCEF.
// Possible values are:
// - SESSION_TERMINATION: Indicates that Rx session is terminated.
// - LOSS_OF_BEARER : Indicates a loss of a bearer.
// - RECOVERY_OF_BEARER: Indicates a recovery of a bearer.
// - RELEASE_OF_BEARER: Indicates a release of a bearer.
// - USAGE_REPORT: Indicates the usage report event.
// - FAILED_RESOURCES_ALLOCATION: Indicates the resource allocation is failed.
// - SUCCESSFUL_RESOURCES_ALLOCATION: Indicates the resource allocation is successful.
type Event struct {
	union json.RawMessage
}

// Event0 defines model for Event.0.
type Event0 string

// Event1 This string provides forward-compatibility with future extensions to the enumeration and is not used to encode content defined in the present version of this API.
type Event1 = string

// EventReport Represents an event report.
type EventReport struct {
	// AccumulatedUsage Represents an accumulated usage.
	AccumulatedUsage *AccumulatedUsage `json:"accumulatedUsage,omitempty"`

	// Event Represents the event reported by the SCEF.
	// Possible values are:
	// - SESSION_TERMINATION: Indicates that Rx session is terminated.
	// - LOSS_OF_BEARER : Indicates a loss of a bearer.
	// - RECOVERY_OF_BEARER: Indicates a recovery of a bearer.
	// - RELEASE_OF_BEARER: Indicates a release of a bearer.
	// - USAGE_REPORT: Indicates the usage report event.
	// - FAILED_RESOURCES_ALLOCATION: Indicates the resource allocation is failed.
	// - SUCCESSFUL_RESOURCES_ALLOCATION: Indicates the resource allocation is successful.
	Event Event `json:"event"`

	// FlowIds Identifies the IP flows that were sent during event subscription
	FlowIds *[]int `json:"flowIds,omitempty"`
}

// ExternalId string containing a local identifier followed by "@" and a domain identifier. Both the local identifier and the domain identifier shall be encoded as strings that do not contain any "@" characters. See Clause 4.6.2 of 3GPP TS 23.682 for more information.
type ExternalId = string

// FlowInfo Represents IP flow information.
type FlowInfo struct {
	// FlowDescriptions Indicates the packet filters of the IP flow. Refer to clause 5.3.8 of 3GPP TS 29.214 for encoding. It shall contain UL and/or DL IP flow description.
	FlowDescriptions *[]string `json:"flowDescriptions,omitempty"`

	// FlowId Indicates the IP flow identifier.
	FlowId int `json:"flowId"`

	// TosTC 2-octet string, where each octet is encoded in hexadecimal representation. The first octet contains the IPv4 Type-of-Service or the IPv6 Traffic-Class field and the second octet contains the ToS/Traffic Class mask field.
	TosTC *TosTrafficClass `json:"tosTC,omitempty"`
}

// LocationArea Represents a user location area.
type LocationArea struct {
	// CellIds Indicates a list of Cell Global Identities of the user which identifies the cell the UE is registered.
	CellIds *[]string `json:"cellIds,omitempty"`

	// CivicAddresses Identifies a list of civic addresses of the user where the UE is located.
	CivicAddresses *[]CivicAddress `json:"civicAddresses,omitempty"`

	// EnodeBIds Indicates a list of eNodeB identities in which the UE is currently located.
	EnodeBIds *[]string `json:"enodeBIds,omitempty"`

	// GeographicAreas Identifies a list of geographic area of the user where the UE is located.
	GeographicAreas *[]GeographicArea `json:"geographicAreas,omitempty"`

	// RoutingAreaIds Identifies a list of Routing Area Identities of the user where the UE is located.
	RoutingAreaIds *[]string `json:"routingAreaIds,omitempty"`

	// TrackingAreaIds Identifies a list of Tracking Area Identities of the user where the UE is located.
	TrackingAreaIds *[]string `json:"trackingAreaIds,omitempty"`
}

// LocationArea5G Represents a user location area when the UE is attached to 5G.
type LocationArea5G struct {
	// CivicAddresses Identifies a list of civic addresses of the user where the UE is located.
	CivicAddresses *[]CivicAddress `json:"civicAddresses,omitempty"`

	// GeographicAreas Identifies a list of geographic area of the user where the UE is located.
	GeographicAreas *[]GeographicArea `json:"geographicAreas,omitempty"`

	// NwAreaInfo Describes a network area information in which the NF service consumer requests the number of UEs.
	NwAreaInfo *NetworkAreaInfo `json:"nwAreaInfo,omitempty"`
}

// Msisdn string formatted according to clause 3.3 of 3GPP TS 23.003 that describes an MSISDN.
type Msisdn = string

// NotificationData Represents the information to be conveyed in a bearer level event(s) notification.
type NotificationData struct {
	// EventReports Contains the reported event and applicable information
	EventReports []EventReport `json:"eventReports"`

	// Transaction string formatted according to IETF RFC 3986 identifying a referenced resource.
	Transaction Link `json:"transaction"`
}

// ResourceId string chosen by the SCEF to serve as identifier in a resource URI.
type ResourceId = string

// ResultReason Represents a failure result reason.
// Possible values are:
//   - ROAMING_NOT_ALLOWED: Identifies the configuration parameters are not allowed by roaming
//     agreement.
//   - OTHER_REASON: Identifies the configuration parameters are not configured due to other
//     reason.
type ResultReason struct {
	union json.RawMessage
}

// ResultReason0 defines model for ResultReason.0.
type ResultReason0 string

// ResultReason1 This string provides forward-compatibility with future extensions to the enumeration and is not used to encode content defined in the present version of this API.
type ResultReason1 = string

// ScsAsId string that identifies an SCS/AS.
type ScsAsId = string

// SponsorInformation Represents a sponsor information.
type SponsorInformation struct {
	// AspId It indicates Application Service Provider ID.
	AspId string `json:"aspId"`

	// SponsorId It indicates Sponsor ID.
	SponsorId string `json:"sponsorId"`
}

// TestNotification Represents a notification that can be sent to test whether a chosen notification mechanism works.
type TestNotification struct {
	// Subscription string formatted according to IETF RFC 3986 identifying a referenced resource.
	Subscription Link `json:"subscription"`
}

// TimeWindow Represents a time window identified by a start time and a stop time.
type TimeWindow struct {
	// StartTime string with format "date-time" as defined in OpenAPI.
	StartTime DateTime `json:"startTime"`

	// StopTime string with format "date-time" as defined in OpenAPI.
	StopTime DateTime `json:"stopTime"`
}

// UsageThreshold Represents a usage threshold.
type UsageThreshold struct {
	// DownlinkVolume Unsigned integer identifying a volume in units of bytes.
	DownlinkVolume *Volume `json:"downlinkVolume,omitempty"`

	// Duration Unsigned integer identifying a period of time in units of seconds.
	Duration *DurationSec `json:"duration,omitempty"`

	// TotalVolume Unsigned integer identifying a volume in units of bytes.
	TotalVolume *Volume `json:"totalVolume,omitempty"`

	// UplinkVolume Unsigned integer identifying a volume in units of bytes.
	UplinkVolume *Volume `json:"uplinkVolume,omitempty"`
}

// UsageThresholdRm Represents the same as the UsageThreshold data type but with the nullable:true property.
type UsageThresholdRm struct {
	// DownlinkVolume Unsigned integer identifying a volume in units of bytes with "nullable=true" property.
	DownlinkVolume *VolumeRm `json:"downlinkVolume,omitempty"`

	// Duration Unsigned integer identifying a period of time in units of seconds with "nullable=true" property.
	Duration *DurationSecRm `json:"duration,omitempty"`

	// TotalVolume Unsigned integer identifying a volume in units of bytes with "nullable=true" property.
	TotalVolume *VolumeRm `json:"totalVolume,omitempty"`

	// UplinkVolume Unsigned integer identifying a volume in units of bytes with "nullable=true" property.
	UplinkVolume *VolumeRm `json:"uplinkVolume,omitempty"`
}

// Volume Unsigned integer identifying a volume in units of bytes.
type Volume = int64

// VolumeRm Unsigned integer identifying a volume in units of bytes with "nullable=true" property.
type VolumeRm = int64

// WebsockNotifConfig Represents the configuration information for the delivery of notifications over Websockets.
type WebsockNotifConfig struct {
	// RequestWebsocketUri Set by the SCS/AS to indicate that the Websocket delivery is requested.
	RequestWebsocketUri *bool `json:"requestWebsocketUri,omitempty"`

	// WebsocketUri string formatted according to IETF RFC 3986 identifying a referenced resource.
	WebsocketUri *Link `json:"websocketUri,omitempty"`
}

// AsConfigResult0 returns the union data inside the ConfigResult as a ConfigResult0
func (t ConfigResult) AsConfigResult0() (ConfigResult0, error) {
	var body ConfigResult0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConfigResult0 overwrites any union data inside the ConfigResult as the provided ConfigResult0
func (t *ConfigResult) FromConfigResult0(v ConfigResult0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConfigResult0 performs a merge with any union data inside the ConfigResult, using the provided ConfigResult0
func (t *ConfigResult) MergeConfigResult0(v ConfigResult0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConfigResult1 returns the union data inside the ConfigResult as a ConfigResult1
func (t ConfigResult) AsConfigResult1() (ConfigResult1, error) {
	var body ConfigResult1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConfigResult1 overwrites any union data inside the ConfigResult as the provided ConfigResult1
func (t *ConfigResult) FromConfigResult1(v ConfigResult1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConfigResult1 performs a merge with any union data inside the ConfigResult, using the provided ConfigResult1
func (t *ConfigResult) MergeConfigResult1(v ConfigResult1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ConfigResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.ExternalIds != nil {
		object["externalIds"], err = json.Marshal(t.ExternalIds)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'externalIds': %w", err)
		}
	}

	if t.Msisdns != nil {
		object["msisdns"], err = json.Marshal(t.Msisdns)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'msisdns': %w", err)
		}
	}

	object["resultReason"], err = json.Marshal(t.ResultReason)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'resultReason': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *ConfigResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["externalIds"]; found {
		err = json.Unmarshal(raw, &t.ExternalIds)
		if err != nil {
			return fmt.Errorf("error reading 'externalIds': %w", err)
		}
	}

	if raw, found := object["msisdns"]; found {
		err = json.Unmarshal(raw, &t.Msisdns)
		if err != nil {
			return fmt.Errorf("error reading 'msisdns': %w", err)
		}
	}

	if raw, found := object["resultReason"]; found {
		err = json.Unmarshal(raw, &t.ResultReason)
		if err != nil {
			return fmt.Errorf("error reading 'resultReason': %w", err)
		}
	}

	return err
}

// AsEvent0 returns the union data inside the Event as a Event0
func (t Event) AsEvent0() (Event0, error) {
	var body Event0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEvent0 overwrites any union data inside the Event as the provided Event0
func (t *Event) FromEvent0(v Event0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEvent0 performs a merge with any union data inside the Event, using the provided Event0
func (t *Event) MergeEvent0(v Event0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEvent1 returns the union data inside the Event as a Event1
func (t Event) AsEvent1() (Event1, error) {
	var body Event1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEvent1 overwrites any union data inside the Event as the provided Event1
func (t *Event) FromEvent1(v Event1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEvent1 performs a merge with any union data inside the Event, using the provided Event1
func (t *Event) MergeEvent1(v Event1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Event) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Event) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResultReason0 returns the union data inside the ResultReason as a ResultReason0
func (t ResultReason) AsResultReason0() (ResultReason0, error) {
	var body ResultReason0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResultReason0 overwrites any union data inside the ResultReason as the provided ResultReason0
func (t *ResultReason) FromResultReason0(v ResultReason0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResultReason0 performs a merge with any union data inside the ResultReason, using the provided ResultReason0
func (t *ResultReason) MergeResultReason0(v ResultReason0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResultReason1 returns the union data inside the ResultReason as a ResultReason1
func (t ResultReason) AsResultReason1() (ResultReason1, error) {
	var body ResultReason1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResultReason1 overwrites any union data inside the ResultReason as the provided ResultReason1
func (t *ResultReason) FromResultReason1(v ResultReason1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResultReason1 performs a merge with any union data inside the ResultReason, using the provided ResultReason1
func (t *ResultReason) MergeResultReason1(v ResultReason1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ResultReason) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ResultReason) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
