// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package gppmodel

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/runtime"
)

// Defines values for PendingNotificationCause0.
const (
	PendingNotificationCause0OTHER                PendingNotificationCause0 = "OTHER"
	PendingNotificationCause0UEOUTOFNFSERVINGAREA PendingNotificationCause0 = "UE_OUT_OF_NF_SERVING_AREA"
)

// Valid indicates whether the value is a known member of the PendingNotificationCause0 enum.
func (e PendingNotificationCause0) Valid() bool {
	switch e {
	case PendingNotificationCause0OTHER:
		return true
	case PendingNotificationCause0UEOUTOFNFSERVINGAREA:
		return true
	default:
		return false
	}
}

// NnwdafDataManagementNotif Represents an Individual Notification.
type NnwdafDataManagementNotif struct {
	// DataNotification Represents a Data Subscription Notification.
	DataNotification *DataNotification `json:"dataNotification,omitempty"`

	// DataReports List of summary reports of processed notifications.
	DataReports *[]NotifSummaryReport `json:"dataReports,omitempty"`

	// DelAlert Contains information about data or analytics that are about to be deleted.
	DelAlert *DeletionAlert `json:"delAlert,omitempty"`

	// FetchInstruct The fetch instructions indicate whether the data or analytics are to be fetched by the consumer.
	FetchInstruct *FetchInstruction `json:"fetchInstruct,omitempty"`

	// NotifCorrId Notification correlation identifier.
	NotifCorrId string `json:"notifCorrId"`

	// NotifTimestamp string with format 'date-time' as defined in OpenAPI.
	NotifTimestamp DateTime `json:"notifTimestamp"`

	// PendNotifCause Represents the Pending Notification Cause for the stored unsent data.
	// Possible values are:
	//   - UE_OUT_OF_NF_SERVING_AREA: The UE moved out of the NF serving area.
	//   - OTHER: Other cause.
	PendNotifCause *PendingNotificationCause `json:"pendNotifCause,omitempty"`

	// TerminationReq It indicates that the termination of the data management subscription is requested by the NWDAF.
	TerminationReq *string `json:"terminationReq,omitempty"`
	union          json.RawMessage
}

// NnwdafDataManagementNotif0 defines model for .
type NnwdafDataManagementNotif0 = interface{}

// NnwdafDataManagementNotif1 defines model for .
type NnwdafDataManagementNotif1 = interface{}

// NnwdafDataManagementNotif2 defines model for .
type NnwdafDataManagementNotif2 = interface{}

// NnwdafDataManagementSubsc Represents an Individual NWDAF Data Management Subscription resource.
type NnwdafDataManagementSubsc struct {
	// AdrfId String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.
	AdrfId *NfInstanceId `json:"adrfId,omitempty"`

	// AdrfSetId NF Set Identifier (see clause 28.12 of 3GPP TS 23.003), formatted as the following string "set<Set ID>.<nftype>set.5gc.mnc<MNC>.mcc<MCC>", or  "set<SetID>.<NFType>set.5gc.nid<NID>.mnc<MNC>.mcc<MCC>" with  <MCC> encoded as defined in clause 5.4.2 ("Mcc" data type definition)  <MNC> encoding the Mobile Network Code part of the PLMN, comprising 3 digits.
	//   If there are only 2 significant digits in the MNC, one "0" digit shall be inserted
	//   at the left side to fill the 3 digits coding of MNC.  Pattern: '^[0-9]{3}$'
	// <NFType> encoded as a value defined in Table 6.1.6.3.3-1 of 3GPP TS 29.510 but
	//   with lower case characters <Set ID> encoded as a string of characters consisting of
	//   alphabetic characters (A-Z and a-z), digits (0-9) and/or the hyphen (-) and that
	//   shall end with either an alphabetic character or a digit.
	AdrfSetId *NfSetId `json:"adrfSetId,omitempty"`

	// AnaSub Represents an Individual NWDAF Event Subscription resource.
	AnaSub *NnwdafEventsSubscription `json:"anaSub,omitempty"`

	// CheckedConsentInd Indication that the NF service consumer has already checked the user consent.
	CheckedConsentInd *bool `json:"checkedConsentInd,omitempty"`

	// DataCollectPurposes The purposes of data collection. This attribute may only be provided if user consent is reqiured depending on local policy and regulations and the consumer has not checked user consent.
	DataCollectPurposes *[]DataCollectionPurpose `json:"dataCollectPurposes,omitempty"`

	// DataSub Contains a data specification.
	DataSub *DataSubscription `json:"dataSub,omitempty"`

	// FormatInstruct Contains data or analytics formatting instructions.
	FormatInstruct *FormattingInstruction `json:"formatInstruct,omitempty"`

	// ImmReport Represents an Individual Notification.
	ImmReport *NnwdafDataManagementNotif `json:"immReport,omitempty"`

	// MultiProcInstructs Processing instructions to be used for sending event notifications.
	MultiProcInstructs *[]ProcessingInstruction `json:"multiProcInstructs,omitempty"`

	// NotifCorrId Notification correlation identifier.
	NotifCorrId string `json:"notifCorrId"`

	// NotifEndpoints The information of notification endpoints.
	NotifEndpoints *[]NotifyEndpoint `json:"notifEndpoints,omitempty"`

	// NotificURI String providing an URI formatted according to RFC 3986.
	NotificURI Uri `json:"notificURI"`

	// ProcInstruct Contains instructions related to the processing of notifications.
	ProcInstruct *ProcessingInstruction `json:"procInstruct,omitempty"`

	// StoreHandl Contains storage handling information about data or analytics.
	StoreHandl *StorageHandlingInformation `json:"storeHandl,omitempty"`

	// SuppFeat A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of "0" to "9",  "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
	SuppFeat *SupportedFeatures `json:"suppFeat,omitempty"`

	// TargetNfId String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.
	TargetNfId *NfInstanceId `json:"targetNfId,omitempty"`

	// TargetNfSetId NF Set Identifier (see clause 28.12 of 3GPP TS 23.003), formatted as the following string "set<Set ID>.<nftype>set.5gc.mnc<MNC>.mcc<MCC>", or  "set<SetID>.<NFType>set.5gc.nid<NID>.mnc<MNC>.mcc<MCC>" with  <MCC> encoded as defined in clause 5.4.2 ("Mcc" data type definition)  <MNC> encoding the Mobile Network Code part of the PLMN, comprising 3 digits.
	//   If there are only 2 significant digits in the MNC, one "0" digit shall be inserted
	//   at the left side to fill the 3 digits coding of MNC.  Pattern: '^[0-9]{3}$'
	// <NFType> encoded as a value defined in Table 6.1.6.3.3-1 of 3GPP TS 29.510 but
	//   with lower case characters <Set ID> encoded as a string of characters consisting of
	//   alphabetic characters (A-Z and a-z), digits (0-9) and/or the hyphen (-) and that
	//   shall end with either an alphabetic character or a digit.
	TargetNfSetId *NfSetId `json:"targetNfSetId,omitempty"`

	// TimePeriod Represents a time window identified by a start time and a stop time.
	TimePeriod *TimeWindow `json:"timePeriod,omitempty"`
	union      json.RawMessage
}

// NnwdafDataManagementSubsc0 defines model for .
type NnwdafDataManagementSubsc0 = interface{}

// NnwdafDataManagementSubsc1 defines model for .
type NnwdafDataManagementSubsc1 = interface{}

// PendingNotificationCause Represents the Pending Notification Cause for the stored unsent data.
// Possible values are:
//   - UE_OUT_OF_NF_SERVING_AREA: The UE moved out of the NF serving area.
//   - OTHER: Other cause.
type PendingNotificationCause struct {
	union json.RawMessage
}

// PendingNotificationCause0 defines model for PendingNotificationCause.0.
type PendingNotificationCause0 string

// PendingNotificationCause1 This string provides forward-compatibility with future extensions to the enumeration but is not used to encode content defined in the present version of this API.
type PendingNotificationCause1 = string

// CreateIndividualSubcriptionJSONRequestBody defines body for CreateIndividualSubcription for application/json ContentType.
type CreateIndividualSubcriptionJSONRequestBody = NnwdafDataManagementSubsc

// UpdateNWDAFDataSubscriptionJSONRequestBody defines body for UpdateNWDAFDataSubscription for application/json ContentType.
type UpdateNWDAFDataSubscriptionJSONRequestBody = NnwdafDataManagementSubsc

// AsNnwdafDataManagementNotif0 returns the union data inside the NnwdafDataManagementNotif as a NnwdafDataManagementNotif0
func (t NnwdafDataManagementNotif) AsNnwdafDataManagementNotif0() (NnwdafDataManagementNotif0, error) {
	var body NnwdafDataManagementNotif0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNnwdafDataManagementNotif0 overwrites any union data inside the NnwdafDataManagementNotif as the provided NnwdafDataManagementNotif0
func (t *NnwdafDataManagementNotif) FromNnwdafDataManagementNotif0(v NnwdafDataManagementNotif0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNnwdafDataManagementNotif0 performs a merge with any union data inside the NnwdafDataManagementNotif, using the provided NnwdafDataManagementNotif0
func (t *NnwdafDataManagementNotif) MergeNnwdafDataManagementNotif0(v NnwdafDataManagementNotif0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNnwdafDataManagementNotif1 returns the union data inside the NnwdafDataManagementNotif as a NnwdafDataManagementNotif1
func (t NnwdafDataManagementNotif) AsNnwdafDataManagementNotif1() (NnwdafDataManagementNotif1, error) {
	var body NnwdafDataManagementNotif1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNnwdafDataManagementNotif1 overwrites any union data inside the NnwdafDataManagementNotif as the provided NnwdafDataManagementNotif1
func (t *NnwdafDataManagementNotif) FromNnwdafDataManagementNotif1(v NnwdafDataManagementNotif1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNnwdafDataManagementNotif1 performs a merge with any union data inside the NnwdafDataManagementNotif, using the provided NnwdafDataManagementNotif1
func (t *NnwdafDataManagementNotif) MergeNnwdafDataManagementNotif1(v NnwdafDataManagementNotif1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNnwdafDataManagementNotif2 returns the union data inside the NnwdafDataManagementNotif as a NnwdafDataManagementNotif2
func (t NnwdafDataManagementNotif) AsNnwdafDataManagementNotif2() (NnwdafDataManagementNotif2, error) {
	var body NnwdafDataManagementNotif2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNnwdafDataManagementNotif2 overwrites any union data inside the NnwdafDataManagementNotif as the provided NnwdafDataManagementNotif2
func (t *NnwdafDataManagementNotif) FromNnwdafDataManagementNotif2(v NnwdafDataManagementNotif2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNnwdafDataManagementNotif2 performs a merge with any union data inside the NnwdafDataManagementNotif, using the provided NnwdafDataManagementNotif2
func (t *NnwdafDataManagementNotif) MergeNnwdafDataManagementNotif2(v NnwdafDataManagementNotif2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NnwdafDataManagementNotif) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.DataNotification != nil {
		object["dataNotification"], err = json.Marshal(t.DataNotification)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dataNotification': %w", err)
		}
	}

	if t.DataReports != nil {
		object["dataReports"], err = json.Marshal(t.DataReports)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dataReports': %w", err)
		}
	}

	if t.DelAlert != nil {
		object["delAlert"], err = json.Marshal(t.DelAlert)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'delAlert': %w", err)
		}
	}

	if t.FetchInstruct != nil {
		object["fetchInstruct"], err = json.Marshal(t.FetchInstruct)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fetchInstruct': %w", err)
		}
	}

	object["notifCorrId"], err = json.Marshal(t.NotifCorrId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'notifCorrId': %w", err)
	}

	object["notifTimestamp"], err = json.Marshal(t.NotifTimestamp)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'notifTimestamp': %w", err)
	}

	if t.PendNotifCause != nil {
		object["pendNotifCause"], err = json.Marshal(t.PendNotifCause)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pendNotifCause': %w", err)
		}
	}

	if t.TerminationReq != nil {
		object["terminationReq"], err = json.Marshal(t.TerminationReq)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'terminationReq': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *NnwdafDataManagementNotif) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["dataNotification"]; found {
		err = json.Unmarshal(raw, &t.DataNotification)
		if err != nil {
			return fmt.Errorf("error reading 'dataNotification': %w", err)
		}
	}

	if raw, found := object["dataReports"]; found {
		err = json.Unmarshal(raw, &t.DataReports)
		if err != nil {
			return fmt.Errorf("error reading 'dataReports': %w", err)
		}
	}

	if raw, found := object["delAlert"]; found {
		err = json.Unmarshal(raw, &t.DelAlert)
		if err != nil {
			return fmt.Errorf("error reading 'delAlert': %w", err)
		}
	}

	if raw, found := object["fetchInstruct"]; found {
		err = json.Unmarshal(raw, &t.FetchInstruct)
		if err != nil {
			return fmt.Errorf("error reading 'fetchInstruct': %w", err)
		}
	}

	if raw, found := object["notifCorrId"]; found {
		err = json.Unmarshal(raw, &t.NotifCorrId)
		if err != nil {
			return fmt.Errorf("error reading 'notifCorrId': %w", err)
		}
	}

	if raw, found := object["notifTimestamp"]; found {
		err = json.Unmarshal(raw, &t.NotifTimestamp)
		if err != nil {
			return fmt.Errorf("error reading 'notifTimestamp': %w", err)
		}
	}

	if raw, found := object["pendNotifCause"]; found {
		err = json.Unmarshal(raw, &t.PendNotifCause)
		if err != nil {
			return fmt.Errorf("error reading 'pendNotifCause': %w", err)
		}
	}

	if raw, found := object["terminationReq"]; found {
		err = json.Unmarshal(raw, &t.TerminationReq)
		if err != nil {
			return fmt.Errorf("error reading 'terminationReq': %w", err)
		}
	}

	return err
}

// AsNnwdafDataManagementSubsc0 returns the union data inside the NnwdafDataManagementSubsc as a NnwdafDataManagementSubsc0
func (t NnwdafDataManagementSubsc) AsNnwdafDataManagementSubsc0() (NnwdafDataManagementSubsc0, error) {
	var body NnwdafDataManagementSubsc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNnwdafDataManagementSubsc0 overwrites any union data inside the NnwdafDataManagementSubsc as the provided NnwdafDataManagementSubsc0
func (t *NnwdafDataManagementSubsc) FromNnwdafDataManagementSubsc0(v NnwdafDataManagementSubsc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNnwdafDataManagementSubsc0 performs a merge with any union data inside the NnwdafDataManagementSubsc, using the provided NnwdafDataManagementSubsc0
func (t *NnwdafDataManagementSubsc) MergeNnwdafDataManagementSubsc0(v NnwdafDataManagementSubsc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNnwdafDataManagementSubsc1 returns the union data inside the NnwdafDataManagementSubsc as a NnwdafDataManagementSubsc1
func (t NnwdafDataManagementSubsc) AsNnwdafDataManagementSubsc1() (NnwdafDataManagementSubsc1, error) {
	var body NnwdafDataManagementSubsc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNnwdafDataManagementSubsc1 overwrites any union data inside the NnwdafDataManagementSubsc as the provided NnwdafDataManagementSubsc1
func (t *NnwdafDataManagementSubsc) FromNnwdafDataManagementSubsc1(v NnwdafDataManagementSubsc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNnwdafDataManagementSubsc1 performs a merge with any union data inside the NnwdafDataManagementSubsc, using the provided NnwdafDataManagementSubsc1
func (t *NnwdafDataManagementSubsc) MergeNnwdafDataManagementSubsc1(v NnwdafDataManagementSubsc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NnwdafDataManagementSubsc) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.AdrfId != nil {
		object["adrfId"], err = json.Marshal(t.AdrfId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'adrfId': %w", err)
		}
	}

	if t.AdrfSetId != nil {
		object["adrfSetId"], err = json.Marshal(t.AdrfSetId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'adrfSetId': %w", err)
		}
	}

	if t.AnaSub != nil {
		object["anaSub"], err = json.Marshal(t.AnaSub)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'anaSub': %w", err)
		}
	}

	if t.CheckedConsentInd != nil {
		object["checkedConsentInd"], err = json.Marshal(t.CheckedConsentInd)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'checkedConsentInd': %w", err)
		}
	}

	if t.DataCollectPurposes != nil {
		object["dataCollectPurposes"], err = json.Marshal(t.DataCollectPurposes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dataCollectPurposes': %w", err)
		}
	}

	if t.DataSub != nil {
		object["dataSub"], err = json.Marshal(t.DataSub)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dataSub': %w", err)
		}
	}

	if t.FormatInstruct != nil {
		object["formatInstruct"], err = json.Marshal(t.FormatInstruct)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'formatInstruct': %w", err)
		}
	}

	if t.ImmReport != nil {
		object["immReport"], err = json.Marshal(t.ImmReport)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'immReport': %w", err)
		}
	}

	if t.MultiProcInstructs != nil {
		object["multiProcInstructs"], err = json.Marshal(t.MultiProcInstructs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'multiProcInstructs': %w", err)
		}
	}

	object["notifCorrId"], err = json.Marshal(t.NotifCorrId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'notifCorrId': %w", err)
	}

	if t.NotifEndpoints != nil {
		object["notifEndpoints"], err = json.Marshal(t.NotifEndpoints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'notifEndpoints': %w", err)
		}
	}

	object["notificURI"], err = json.Marshal(t.NotificURI)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'notificURI': %w", err)
	}

	if t.ProcInstruct != nil {
		object["procInstruct"], err = json.Marshal(t.ProcInstruct)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'procInstruct': %w", err)
		}
	}

	if t.StoreHandl != nil {
		object["storeHandl"], err = json.Marshal(t.StoreHandl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'storeHandl': %w", err)
		}
	}

	if t.SuppFeat != nil {
		object["suppFeat"], err = json.Marshal(t.SuppFeat)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'suppFeat': %w", err)
		}
	}

	if t.TargetNfId != nil {
		object["targetNfId"], err = json.Marshal(t.TargetNfId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'targetNfId': %w", err)
		}
	}

	if t.TargetNfSetId != nil {
		object["targetNfSetId"], err = json.Marshal(t.TargetNfSetId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'targetNfSetId': %w", err)
		}
	}

	if t.TimePeriod != nil {
		object["timePeriod"], err = json.Marshal(t.TimePeriod)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'timePeriod': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *NnwdafDataManagementSubsc) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["adrfId"]; found {
		err = json.Unmarshal(raw, &t.AdrfId)
		if err != nil {
			return fmt.Errorf("error reading 'adrfId': %w", err)
		}
	}

	if raw, found := object["adrfSetId"]; found {
		err = json.Unmarshal(raw, &t.AdrfSetId)
		if err != nil {
			return fmt.Errorf("error reading 'adrfSetId': %w", err)
		}
	}

	if raw, found := object["anaSub"]; found {
		err = json.Unmarshal(raw, &t.AnaSub)
		if err != nil {
			return fmt.Errorf("error reading 'anaSub': %w", err)
		}
	}

	if raw, found := object["checkedConsentInd"]; found {
		err = json.Unmarshal(raw, &t.CheckedConsentInd)
		if err != nil {
			return fmt.Errorf("error reading 'checkedConsentInd': %w", err)
		}
	}

	if raw, found := object["dataCollectPurposes"]; found {
		err = json.Unmarshal(raw, &t.DataCollectPurposes)
		if err != nil {
			return fmt.Errorf("error reading 'dataCollectPurposes': %w", err)
		}
	}

	if raw, found := object["dataSub"]; found {
		err = json.Unmarshal(raw, &t.DataSub)
		if err != nil {
			return fmt.Errorf("error reading 'dataSub': %w", err)
		}
	}

	if raw, found := object["formatInstruct"]; found {
		err = json.Unmarshal(raw, &t.FormatInstruct)
		if err != nil {
			return fmt.Errorf("error reading 'formatInstruct': %w", err)
		}
	}

	if raw, found := object["immReport"]; found {
		err = json.Unmarshal(raw, &t.ImmReport)
		if err != nil {
			return fmt.Errorf("error reading 'immReport': %w", err)
		}
	}

	if raw, found := object["multiProcInstructs"]; found {
		err = json.Unmarshal(raw, &t.MultiProcInstructs)
		if err != nil {
			return fmt.Errorf("error reading 'multiProcInstructs': %w", err)
		}
	}

	if raw, found := object["notifCorrId"]; found {
		err = json.Unmarshal(raw, &t.NotifCorrId)
		if err != nil {
			return fmt.Errorf("error reading 'notifCorrId': %w", err)
		}
	}

	if raw, found := object["notifEndpoints"]; found {
		err = json.Unmarshal(raw, &t.NotifEndpoints)
		if err != nil {
			return fmt.Errorf("error reading 'notifEndpoints': %w", err)
		}
	}

	if raw, found := object["notificURI"]; found {
		err = json.Unmarshal(raw, &t.NotificURI)
		if err != nil {
			return fmt.Errorf("error reading 'notificURI': %w", err)
		}
	}

	if raw, found := object["procInstruct"]; found {
		err = json.Unmarshal(raw, &t.ProcInstruct)
		if err != nil {
			return fmt.Errorf("error reading 'procInstruct': %w", err)
		}
	}

	if raw, found := object["storeHandl"]; found {
		err = json.Unmarshal(raw, &t.StoreHandl)
		if err != nil {
			return fmt.Errorf("error reading 'storeHandl': %w", err)
		}
	}

	if raw, found := object["suppFeat"]; found {
		err = json.Unmarshal(raw, &t.SuppFeat)
		if err != nil {
			return fmt.Errorf("error reading 'suppFeat': %w", err)
		}
	}

	if raw, found := object["targetNfId"]; found {
		err = json.Unmarshal(raw, &t.TargetNfId)
		if err != nil {
			return fmt.Errorf("error reading 'targetNfId': %w", err)
		}
	}

	if raw, found := object["targetNfSetId"]; found {
		err = json.Unmarshal(raw, &t.TargetNfSetId)
		if err != nil {
			return fmt.Errorf("error reading 'targetNfSetId': %w", err)
		}
	}

	if raw, found := object["timePeriod"]; found {
		err = json.Unmarshal(raw, &t.TimePeriod)
		if err != nil {
			return fmt.Errorf("error reading 'timePeriod': %w", err)
		}
	}

	return err
}

// AsPendingNotificationCause0 returns the union data inside the PendingNotificationCause as a PendingNotificationCause0
func (t PendingNotificationCause) AsPendingNotificationCause0() (PendingNotificationCause0, error) {
	var body PendingNotificationCause0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPendingNotificationCause0 overwrites any union data inside the PendingNotificationCause as the provided PendingNotificationCause0
func (t *PendingNotificationCause) FromPendingNotificationCause0(v PendingNotificationCause0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePendingNotificationCause0 performs a merge with any union data inside the PendingNotificationCause, using the provided PendingNotificationCause0
func (t *PendingNotificationCause) MergePendingNotificationCause0(v PendingNotificationCause0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPendingNotificationCause1 returns the union data inside the PendingNotificationCause as a PendingNotificationCause1
func (t PendingNotificationCause) AsPendingNotificationCause1() (PendingNotificationCause1, error) {
	var body PendingNotificationCause1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPendingNotificationCause1 overwrites any union data inside the PendingNotificationCause as the provided PendingNotificationCause1
func (t *PendingNotificationCause) FromPendingNotificationCause1(v PendingNotificationCause1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePendingNotificationCause1 performs a merge with any union data inside the PendingNotificationCause, using the provided PendingNotificationCause1
func (t *PendingNotificationCause) MergePendingNotificationCause1(v PendingNotificationCause1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PendingNotificationCause) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PendingNotificationCause) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
